### ISSUE TITLE
existent, unison implementation of `List.empty`

### ISSUE THREAD

**Issue by aryairani** [unisonweb/base_v1#10]
Replaces the reference to unimplemented builtin `##List.empty` with a reference to the term `[]`.

Quick fix for https://github.com/unisonweb/unison/issues/1338

```
.temp> view base.List.empty head.List.empty

  -- base.List.empty is built-in.
  
  head.List.empty : [a]
  head.List.empty = []
```
___

  The changes summarized below are available for you to review, using the following
  command:
  
    pull-request.load https://github.com/unisonweb/base https://github.com/aryairani/base
  
  Updates:
  
     List.empty : [a]
     ↓
     List.empty : [a]
  
  Added definitions:
  
     patch patch (added 1 updates)

**Comment by aryairani** [comment]
Merged https://github.com/unisonweb/base/commit/03359691e15b0b4b419663d860a9cbca5bc98099

**Comment by aryairani** [comment]
Unmerged 03359691e15b0b4b419663d860a9cbca5bc98099 to figure out why it was 112 files instead of ~3.

**Comment by pchiusano** [comment]
Merged: 842c590ae49cb62f6cf92b62c338a096fcb329ce

**Comment by aryairani** [comment]
Wait, why did 842c590 still change 16 files?

**Comment by pchiusano** [comment]
@aryairani I haven't tracked everything down in detail, but 2 namespace additions per change x 3 changes (the update, then two added metadata for author and license), and then some type index and dependents updates.

**Comment by aryairani** [comment]
@pchiusano Ok great thanks.
