### ISSUE TITLE
Adds testing helper, natIn documentation, Char generators.

### ISSUE THREAD

**Issue by pete-ts** [unisonweb/base_v1#14]
## Overview

This `unison pull request` aims to add `Generators` in the  `base.test.v1.Char` namespace, and also adds documentation to the `base.test.v1.natIn` generator.

## Implementation notes

1. adds `(===)` aliased to `equalsOrBug`. This allows testing with `===` that breaks immediately with debug output of the values being compared. The documentation contains an example of the behaviour.
2. add documentation to `natIn`
3. adds a `natIn'` generator, with examples and documentation, that allows a rolling over to the start version of `natIn`.
4. adds generators for `alpha`, `ascii`, `asciiNonPrintable`, `asciiPrintable`, `digit`, `hexDigit`, `upper`, `lower` (all with examples and linked documentation)

## Controversial (?)

I now realise that `===` should have been one PR, `natIn` documentation another, and the `Char.*` generators another still. This was not intentional, and in hindsight probably down to not being as familiar as I should be with namespacing, will do my utmost to avoid scope creep in the future.

## Test coverage

All the methods implemented have been tested, and the `evaluated` values in the documentation have been produced via sampling the generators.

## Code review

  The changes summarized below are available for you to review, using the following command:
  
    pull-request.load https://github.com/unisonweb/base:.test.v1 https://github.com/pete-ts/base:.base.test.v1
  
  Updates:
  
     natIn : Nat -> Nat -> '{Gen} Nat
     +  natIn.doc : Doc
  
  Added definitions:
  
     ┌ ===                                : a -> a -> Boolean (+1 metadata)
     └ equalsOrBug                        : a -> a -> Boolean (+1 metadata)
     Char.alpha                           : '{Gen} Char (+2 metadata)
     Char.alpha.doc                       : Doc
     Char.alpha.examples.some             : [Char]
     Char.ascii                           : '{Gen} Char (+1 metadata)
     Char.ascii.doc                       : Doc (+1 metadata)
     Char.ascii.examples.some             : [Char]
     Char.asciiNonPrintable               : '{Gen} Char (+1 metadata)
     Char.asciiNonPrintable.doc           : Doc
     Char.asciiNonPrintable.examples.some : [Char]
     Char.asciiPrintable                  : '{Gen} Char (+2 metadata)
     Char.asciiPrintable.doc              : Doc
     Char.asciiPrintable.examples.some    : [Char]
     Char.digit                           : '{Gen} Char (+2 metadata)
     Char.digit.doc                       : Doc
     Char.digit.examples.all              : [Char]
     Char.hexDigit                        : '{Gen} Char (+1 metadata)
     Char.hexDigit.doc                    : Doc
     Char.hexDigit.examples.some          : [Char]
     Char.lower                           : '{Gen} Char (+2 metadata)
     Char.lower.doc                       : Doc
     Char.lower.examples.some             : [Char]
     Char.upper                           : '{Gen} Char (+2 metadata)
     Char.upper.doc                       : Doc
     Char.upper.examples.some             : [Char]
     equalsOrBug.doc                      : Doc
     natIn'                               : Nat -> Nat -> '{Gen} Nat (+1 metadata)
     natIn'.doc                           : Doc (+1 metadata)
     natIn'.examples.oneOneTenTimes       : [Nat] (+1 metadata)
     natIn'.examples.oneTenTenTimes       : [Nat] (+1 metadata)
     natIn'.examples.zeroOneOnce          : [Nat] (+1 metadata)
     natIn'.examples.zeroOneTenTimes      : [Nat] (+1 metadata)
     natIn.doc                            : Doc
     natIn.examples.oneOneTenTimes        : [Nat]
     natIn.examples.oneTenTenTimes        : [Nat]
     natIn.examples.zeroOneOnce           : [Nat]
     natIn.examples.zeroOneTenTimes       : [Nat]
  
     patch Char.patch (added 9 updates)
     patch patch (added 10 updates)

**Comment by pchiusano** [comment]
@pete-ts okay, had a look through these - 

- In general, I think none of the primitive generators should be repeating. Instead I'd introduce `cycle : '{Gen} a -> '{Gen} a`, which I'd probably start by using inline before introducing `natIn'` etc.
- If we do decide we also want some primitive generators that repeat, we should have a strong naming convention that makes this clear I think (maybe `cycleNatIn`, `cycleAscii`, etc).
- License and author missing on a few definitions. If you do a `find`, you can probably spot all the definitions you wrote and assign them licenses with one link command. Sorry this is a little tedious, but we are working on it!
- I'd keep all the generator instances within the testing library, so not at the top level `Char.ascii`, but in a subnamespace: `test.v1.gen.Char.ascii` etc. I don't mind fixing this up though, it's pretty cool that we can just do renaming / shuffling things around after the fact and it doesn't break anything.

**Comment by pete-ts** [comment]
@pchiusano thanks for the feedback.
Let me work on this and I will update when ready :+1:

**Comment by pete-ts** [comment]
Closing the issue, the reworked parts are in #16
