### ISSUE TITLE
Adds List.filter

### ISSUE THREAD

**Issue by pete-ts** [unisonweb/base_v1#17]
## Overview

This PR adds the List.filter function, along with:
* documentation
* a small number of unit tests
* author and license links

## Code review

    pull-request.load https://github.com/unisonweb/base https://github.com/pete-ts/base:.prs.listFilter
  
  Added definitions:
  
     List.filter                : (a ->{𝕖} Boolean) -> [a] ->{𝕖} [a] (+3 metadata)
     List.filter.doc            : Doc
     List.filter.tests.empty    : [Result] (+1 metadata)
     List.filter.tests.negative : [Result] (+1 metadata)
     List.filter.tests.positive : [Result] (+1 metadata)
  
     patch List.patch (added 1 updates)

**Comment by pchiusano** [comment]
Cool! Looks good. Can you just see my note on https://github.com/unisonweb/base/issues/16#issuecomment-613067598 about agreeing to license all the definitions (including the tests and docs) as MIT? Then I can fix up after merging.

**Comment by pete-ts** [comment]
"I agree to license all the definitions listed in this PR with the [MIT license](https://opensource.org/licenses/MIT)"

**Comment by pchiusano** [comment]
Cool. I merged in 51bfda81 which is Unison namespace hash bj58m19j40ltvk3pc2
