### ISSUE TITLE
Documents and unit tests existing Search functions

### ISSUE THREAD

**Issue by pete-ts** [unisonweb/base_v1#18]
## Overview

This PR adds documentation sections for the `Search` functions. The documentation added highlights that `binary search` is used under the hood, and suggests using the search functions only on `sorted` lists. Cornercases added to specifically showcase that unless the input is sorted, the functions (as expected) do not find elements that are otherwise in the list.

* Unit tests :heavy_check_mark: 
* Docs linked against functions :heavy_check_mark: 
* Author/Licence :heavy_minus_sign: as these are not mine.

## Code review

  The changes summarized below are available for you to review, using the following command:
  
    pull-request.load https://github.com/unisonweb/base https://github.com/pete-ts/base:.prs.searchDocumentation
  
  Updates:
  
     Search.anyIndexOf : a -> [a] -> Optional Nat
     +  anyIndexOf.doc : Doc
    
     Search.exact : (Nat ->{𝕖} Int) -> Nat -> Nat ->{𝕖} Optional Nat
     +  exact.doc : Doc
    
     Search.lub : (Nat ->{𝕖} Int) -> Nat -> Nat ->{𝕖} Nat
     +  lub.doc : Doc
    
     Search.lubIndexOf : a -> [a] -> Nat
     +  lubIndexOf.doc : Doc
  
     patch patch (added 1 updates)
  
  Added definitions:
  
     patch patch (added 1 updates)
  
  Added definitions:
  
     Search.anyIndexOf.doc                        : Doc
     Search.anyIndexOf.evaluated.empty            : Optional Nat
     Search.anyIndexOf.evaluated.lower            : Optional Nat
     Search.anyIndexOf.evaluated.notSorted        : Optional Nat
     Search.anyIndexOf.evaluated.sorted           : Optional Nat
     Search.anyIndexOf.evaluated.upper            : Optional Nat
     ┌ Search.anyIndexOf.examples.input.lower     : [Nat]
     └ Search.anyIndexOf.examples.input.notSorted : [Nat]
     Search.anyIndexOf.examples.input.upper       : [Nat]
     Search.anyIndexOf.tests.empty                : [Result] (+1 metadata)
     Search.anyIndexOf.tests.lower                : [Result] (+1 metadata)
     Search.anyIndexOf.tests.notSorted            : [Result] (+1 metadata)
     Search.anyIndexOf.tests.sorted               : [Result] (+1 metadata)
     Search.anyIndexOf.tests.upper                : [Result] (+1 metadata)
     Search.exact.doc                             : Doc
     Search.lub.doc                               : Doc
     Search.lubIndexOf'.doc                       : Doc
     Search.lubIndexOf.doc                        : Doc
     Search.lubIndexOf.evaluated.empty            : Nat
     Search.lubIndexOf.evaluated.notSorted        : Nat
     Search.lubIndexOf.evaluated.sorted           : Nat
     Search.lubIndexOf.tests.empty                : [Result] (+1 metadata)
     Search.lubIndexOf.tests.notSorted            : [Result] (+1 metadata)
     Search.lubIndexOf.tests.sorted               : [Result] (+1 metadata)
  
     patch Search.patch (added 7 updates)
  
  Name changes:
  
    Original                     Changes
     List.last.examples.elems     Search.anyIndexOf.examples.input.sorted (added)

**Comment by pete-ts** [comment]
"I agree to license all the definitions listed in this PR with the [MIT license](https://opensource.org/licenses/MIT)"

**Comment by runarorama** [comment]
Merged in base hash #i4v92o9e8.

Thanks @pete-ts! 🦄 🌈 🎉
