### ISSUE TITLE
Testing helper to print debug output on failure.

### ISSUE THREAD

**Issue by pete-ts** [unisonweb/base_v1#20]
## Overview

Adds a `===` operator/test helper to wrap around `Universal.==` and on `false` uses "bug" to show the two values being compared. ("Debug output if my test is failing").

The main reason I am adding this is the fact that I have found myself needing/using it quite frequently. I do not have an opinion/preference on the naming convention (my mind is currently wired on `scala.specs2 must_===` probably), just leaving it here to start a discussion. `check/check'` take an input of `Boolean` so a wrapper around those that takes (`a -> a -> Boolean`) should also be trivial, to have a comparable debug wrapper around `check/check'` too.

* "No point in unit testing": a failure explodes `ucm` and cannot be `add`ed.
* So this behaviour is captured fully in the `.doc`.
* Linked to doc/author/license.

## Code review

  The changes summarized below are available for you to review, using the following
  command:
  
    pull-request.load https://github.com/unisonweb/base https://github.com/pete-ts/base:.prs.tripleEquals
  
  Added definitions:
  
     ┌ test.internals.v1.Test.===           : a -> a -> Boolean (+3 metadata)
     └ test.internals.v1.Test.equalsOrBug   : a -> a -> Boolean (+3 metadata)
     test.internals.v1.Test.equalsOrBug.doc : Doc
  
     patch test.internals.v1.Test.patch (added 1 updates)

**Comment by runarorama** [comment]
Thanks, @pete-ts! I've made a couple of changes to this and merged it in base hash #nq3qvlbnkj.

I added `assert : Boolean -> e -> a -> a` and reimplemented `===` in terms of that. I also renamed `equalsOrBug` to `assertEquals`.

🌈 🦄 🚲
