### ISSUE TITLE
Store ability

### ISSUE THREAD

**Issue by anovstrup** [unisonweb/base_v1#22]
This PR adds a `Store` ability and associated functions (`modify`, `local`, and a `store` handler).

## Code review

  The changes summarized below are available for you to review, using the following command:

    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/anovstrup/unisonweb-base:.prs._storePR

  Added definitions:

     ability Store a (+3 metadata)
     Store.get                         : {Store a} a (+3 metadata)
     Store.put                         : a ->{Store a} () (+3 metadata)
     Store.doc                         : Doc (+2 metadata)
     Store.get.doc                     : Doc (+3 metadata)
     Store.get.examples.ex1            : Nat (+2 metadata)
     Store.local                       : a -> '{g, Store a} v ->{g, Store a} v (+3 metadata)
     Store.local.doc                   : Doc (+3 metadata)
     Store.local.examples.ex1          : (Nat, Nat, Nat) (+2 metadata)
     Store.local.test                  : [Result] (+3 metadata)
     Store.modify                      : (a ->{g} a) ->{g, Store a} () (+3 metadata)
     Store.modify.doc                  : Doc (+3 metadata)
     Store.modify.examples.increment   : Nat (+3 metadata)
     Store.modify.test                 : [Result] (+3 metadata)
     Store.put.doc                     : Doc (+3 metadata)
     Store.put.examples.ex1            : Nat (+2 metadata)
     Store.withInitialValue            : a -> '{g, Store a} v ->{g} v (+4 metadata)
     Store.withInitialValue.doc        : Doc (+3 metadata)
     Store.withInitialValue.handler    : a -> Request (Store a) v -> v (+2 metadata)
     Store.withInitialValue.laws.law1  : a ->{Store a} Test (+2 metadata)
     Store.withInitialValue.tests.law1 : [Result] (+3 metadata)

**Comment by pchiusano** [comment]
@anovstrup cool! A couple things:

If you aren't already, check out the new default metadata stuff! https://www.unisonweb.org/docs/configuration/ which is in master and also the M1j release.

Can you apply `.patches.dev` (in latest `base`) to your definitions? It generalizes `runs` which is used by your tests: https://www.unisonweb.org/docs/codebase-organization#keeping-in-sync-with-trunk

Can you generalize / widen the signatures of these functions?

```
Store.local : a -> '{Store a} v ->{Store a} v
```

That can be:

```
Store.local : a -> '{g, Store a} v ->{g, Store a} v
```

Which is handy if you want to use `Store` with other abilities. :)

* `modify` can get the same treatment (should work with a function `a ->{g} a`).
* `store` can get the same treatment (should work with a `'{g, Store a} v`)
* The signature on `Store.store.handler` shouldn't require the `e` after just 1 argument, only after the second argument. Not exactly wrong but less flexible. Known inference bug. Can you try adding an explicit signature to that definition?

**Comment by anovstrup** [comment]
@pchiusano I made the requested changes, renamed `Store.store` to `Store.withInitialValue`, and added a few tiny tests and documentation for the `Store` ability itself.

**Comment by pchiusano** [comment]
Looks great @anovstrup just merged in Unison namespace hash #ddmhiofsj9
