### ISSUE TITLE
Memo ability

### ISSUE THREAD

**Issue by anovstrup** [unisonweb/base_v1#23]
This PR adds a `Memo` ability for memoization:

```
ability Memo e a where memoize : '{e, Memo e a} a ->{Memo e a} a

Memo.evalOnce : '{e, Memo {e} a} b ->{e} b
...

Memo.evalOnce.handler :
    Map ('{e, Memo {e} a} a) a -> 
    Request (Memo {e} a) b ->{e} 
    (b, Map ('{e, Memo {e} a} a) a)
...

Memo.memoize.examples.memoFib : Nat ->{Memo {} Nat} Nat
Memo.memoize.examples.memoFib n = memoize 'let
  if n == 0 then 1
  else if n == 1 then 1
  else memoFib (drop n 2) + memoFib (drop n 1))

-- `evalOnce` makes `memoFib` efficient
> Memo.evalOnce '(Memo.memoize.examples.memoFib 50)
  ⧩
  20365011074
```

The PR includes a test demonstrating that `Memo.evalOnce` really does evaluate each memoized subcomputation only once. (Evaluating the `memoFib` example also demonstrates this, as an unmemoized recursive implementation has exponential running time.)

I also considered an `Eval` ability that might also be useful. Whereas `Memo` leaves it up to the `handler` to determine what kind of memoization to provide (e.g., permanent storage vs. temporary caching), `Eval` would provide separate operations to offer more control at the call site:

```
ability Eval where 
  always: 'a -> a
  cached: 'a -> a
  once: 'a -> a
```

**Note:** the code in this PR uses some of the definitions in PR #22.

## Code review

  The changes summarized below are available for you to review, using the following command:

    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/anovstrup/unisonweb-base:.prs._memo2

  Added definitions:

     ability Memo e a (+2 metadata)
     Memo.memoize                  : '{e, Memo e a} a ->{Memo e a} a
     Memo.evalOnce                 : '{e, Memo {e} a} b ->{e} b (+3 metadata)
     Memo.evalOnce.doc             : Doc (+2 metadata)
     Memo.evalOnce.handler         : Map '{e, Memo {e} a} a a
                                   -> Request (Memo {e} a) b
                                   ->{e} (b, Map '{e, Memo {e} a} a a) (+2 metadata)
     Memo.evalOnce.test            : [Result] (+4 metadata)
     Memo.memoize.examples.memoFib : Nat ->{Memo {} Nat} Nat (+2 metadata)

  Name changes:

    Original             Changes
     Function.flatMap     bind (added)

**Comment by atacratic** [comment]
This is awesome, I hadn't realised this was possible already.  The magic is that we can apply `Universal.compare` to function types, `'a`.  I think this is a great example of a Unison superpower - would be cool to get it in a tweet or into the next blog post @pchiusano .

It uses `base.Map` which looks like it has O(n) `lookup` (it uses `anyIndexOf` which walks the list of keys) instead of the O(log n) I was expecting.  I think that means that typical applications of `Memo` will end up with quadratic runtime (including the memoFib example?), which is an improvement on exponential but still not great.  Does someone know the plan for `base.Map`?  Or have I misunderstood something?

Assuming Map had O(log n) lookup, I think `evalOnce.doc` should be claiming O(n log n) runtime rather than O(n), because of the lookups. 

The changes in the PR look good to me.

**Comment by anovstrup** [comment]
> It uses `base.Map` which looks like it has O(n) `lookup` (it uses `anyIndexOf` which walks the list of keys) instead of the O(log n) I was expecting. I think that means that typical applications of `Memo` will end up with quadratic runtime (including the memoFib example?), which is an improvement on exponential but still not great. Does someone know the plan for `base.Map`? Or have I misunderstood something?

😬 Oops, I just assumed that `Map` had effectively constant-time lookup like Scala's immutable HashMap. I'll update the doc!

**Comment by atacratic** [comment]
I think the first question is whether/how to fix base.Map! Maybe it was a stopgap or I have misunderstood.

**Comment by anovstrup** [comment]
@atacratic If I'm not mistaken, `Map.lookup` is using `indexOf`, which performs a binary search over the sorted list of keys (with `exact`). I'm not sure what random access costs in `List`, but `Map.lookup` has to be Ω(log(n)).

**Comment by atacratic** [comment]
Ah nice one, yes I had a feeling I must be being silly.  I stopped at `anyIndexOf`, evidently confused, without looking at `exact`...  

Probably Map.lookup is O (log n . log n) since each `List.at` is logarithmic, not that it matters.  Would still be better to avoid claiming O(n) in that doc, I think.

**Comment by anovstrup** [comment]
Fixed the documentation. Rather than try to figure out a precise bound, I changed it to "tractable even for large `n`". :)

**Comment by pchiusano** [comment]
Wow neato I also didn’t realize this was possible..

@atacratic is right, it’s log N^2, the extra log N factor due to list indexing being logarithmic.

We could use a better Map implementation that’s maybe a port of Data.Map. Could save the log factor. Or maybe a finger tree implementation.

**Comment by anovstrup** [comment]
I updated the PR to fix some typing issues so that memoization works correctly with other abilities. Specifically, I parameterized the `Memo` ability by the ability type that `memoize` eliminates and by the result type of each memoized computation. `Memo.evalOnce '(Memo.memoize '(Store.modify Nat.increment))` results in a type error rather than a runtime failure with this new implementation. 
 This `Memo` ability _is_ more limited than the previous one. It's not possible to memoize both a Text-valued computation and a Nat-valued computation in the same context, for instance; however, I think this limitation is necessary in order to type the `Map` arguments in `evalOnce.handler`'s type signature correctly within Unison's type system. (I think it's probably an accident that the previous implementation type-checked, as it would have required Map values with heterogenous keys/values.)

**Comment by pchiusano** [comment]
@anovstrup that makes a lot more sense - I was wondering how it could be possible to memoize differently typed expressions in the same scope. However I think you can get away with just Memo a, where a is the type of the computation being memoized.

**Comment by pchiusano** [comment]
Whoops hit wrong button there and didn’t even finish replying... I think there might be a nice design which doesn’t require picking the inner ability in advance, though. By using an existential type. I’d like to play with it.

**Comment by anovstrup** [comment]
@pchiusano I tried this implementation. I'm not sure whether it's correct, but I can't test it because the typechecker silently fails:

```
ability Memo a where memoize : '{e, Memo a} a ->{e, Memo a} a

Memo.evalOnce.handler :
  Map ('{e, Memo a} a) a
  -> Request {e, Memo a} b
  ->{e} (b, Map ('{e, Memo a} a) a)
Memo.evalOnce.handler m = cases
  { v }                           -> (v, m)
  {Memo.memoize v' -> k} ->
    match Map.lookup v' m with
      Some v -> handle k v with Memo.evalOnce.handler m
      None   ->
        match (handle !v' with Memo.evalOnce.handler m) with
          (v, m2) -> handle k v with Memo.evalOnce.handler (Map.insert v' v m2)
```

**Comment by pchiusano** [comment]
@anovstrup I was messing with this, using an `Exists` type as the key:

```Haskell
type Exists = Exists (forall e r . (forall a . a ->{e} r) ->{e} r)

Exists.existential : a -> Exists
Exists.existential a = Exists.Exists (k -> k a)

unique ability Memo a where
  lookup : Exists -> Optional a
  cache : Exists -> a -> ()

Memo.handler : Map Exists a ->{} Request (Memo a) r ->{} r
Memo.handler m = cases
  { r }                          -> r
  { Memo.lookup any -> k }       ->
    handle k (Map.lookup any m) 
    with Memo.handler m
  { Memo.cache any result -> k } -> 
    handle k () 
    with Memo.handler (Map.insert any result m)

Memo.run : '{Memo a, e} a ->{e} a
Memo.run r = handle !r with Memo.handler Map.empty

Memo.memo : '{e} a ->{Memo a, e} a
Memo.memo a = 
  any = existential a
  match Memo.lookup any with
    None   -> result = !a
              Memo.cache any result
              result
    Some a -> a

fib n = Memo.run '(fib' n)

fib' n = memo 'let
  if n < 2 then n
  else fib' (n `drop` 1) + fib' (n `drop` 2)

> List.map fib (range 0 10)
--     32 | > List.map fib (range 0 10)
--           ⧩
--           [0, 1, 1, 2, 3, 5, 8, 13, 21, 34]
```

This declaration is problematic for the current typechecker. It's a higher order ability and should probably just be rejected with a nice message.

```Haskell
ability Memo a where memoize : '{e, Memo a} a ->{e, Memo a} a
```

I'd avoid abilities with operations that have any other ability requirements besides the ability being declared, and would assume a future version of the typechecker will disallow. Very often, you can express the ability a bit differently to achieve the same ends, like I did above.

**Comment by pchiusano** [comment]
@anovstrup so I think this is pretty cool but that it belongs as a separate little library. Want to create one and link it here? https://www.unisonweb.org/docs/libraries/

Feel free to use any of my code above. I hereby license it using the MIT license: https://opensource.org/licenses/MIT

**Comment by anovstrup** [comment]
@pchiusano I made some changes to your implementation and published it as v1 here: https://github.com/anovstrup/unison-memo

Care to check it out when you get a chance, before we add a link on the libraries page?
