### ISSUE TITLE
Add some basic operations on Set, Map, List

### ISSUE THREAD

**Issue by runarorama** [unisonweb/base_v1#27]
This adds a number of missing operations on functions, Set, List, and Map, along with associated docs.

## Code review

  The changes summarized below are available for you to review, using the following command:

    pull-request.load git@github.com:unisonweb/base.git:.trunk git@github.com:runarorama/mybase.git:.prs._pr27

  Added definitions:

     Function.flatMap     : (a -> r ->{e} b) -> (r ->{e} a) -> r ->{e} b (+3 metadata)
     Function.flatMap.doc : Doc (+2 metadata)
     List.deleteAt        : Nat -> [a] -> [a] (+3 metadata)
     List.deleteAt.doc    : Doc (+2 metadata)
     List.deleteAt.test   : [Result] (+3 metadata)
     Map.delete           : k -> Map k v -> Map k v (+3 metadata)
     Map.delete.doc       : Doc (+2 metadata)
     Map.delete.test      : [Result] (+2 metadata)
     Set.delete           : k -> Set k -> Set k (+3 metadata)
     Set.delete.doc       : Doc (+2 metadata)
     Set.delete.test      : [Result] (+3 metadata)
     Set.map              : (a ->{e} b) -> Set a ->{e} Set b (+3 metadata)
     Set.map.doc          : Doc (+2 metadata)
     Set.map.test         : [Result] (+3 metadata)
     Set.singleton        : a -> Set a (+3 metadata)
     Set.singleton.doc    : Doc (+2 metadata)
     Set.singleton.test   : [Result] (+3 metadata)
     test.mapOf           : '{Gen} k -> '{Gen} v -> '{Gen} Map k v (+3 metadata)
     test.mapOf.doc       : Doc (+2 metadata)
     test.pairOf          : '{Gen} a -> '{Gen} b -> '{Gen} (a, b) (+3 metadata)
     test.pairOf.doc      : Doc (+2 metadata)

  Name changes:

    Original         Changes
     test.list        test.listOf (added)
                      test.list (removed)

     test.set         test.setOf (added)
                      test.set (removed)

     test.set.doc     test.setOf.doc (added)
                      test.set.doc (removed)

**Comment by pchiusano** [comment]
Cool! Nice property for `List.deleteAt`. Could you add:

* A test for `Map.delete`.
* A test for `Set.singleton` (maybe equal to `Set.fromList [a]`)

Not sure `bind` merits a top level name like that. I see that it's reader monad bind. Any objections to: `Function.flatMap` (consistent with `List.flatMap`, `Optional.flatMap`, etc).

It looks like you deleted the patch that was in base. 😕The diff message isn't super clear, but if you `view.patch merged.patch` it's empty where it wasn't in `base`.

I'm guessing you had some local edits from during development which you didn't care about and just wanted to blow them away, but that unfortunately blew away the existing patch which has something we do want.

The suggestion [here](https://www.unisonweb.org/docs/codebase-organization#day-to-day-development-creating-and-merging-pull-requests) which will avoid this is to put new definitions in an empty namespace, with naming parallel to the namespace where you want to merge. You can do whatever development / updating you want in that fresh namespace then delete the patch when you're ready to create the PR. You can also easily squash / discard the history. And it's a little easier to review, too (easy to see test report for just the added tests, easier to do bulk operations on the new definitions during review).

Also, you can catch this pretty easily just by looking at the diff that the PR create gives back. If you're just adding new definitions, there shouldn't be any patch updates.

To fix, I guess you can just `copy.patch` from the current `base` into your PR branch.

Minor: name tests `foo.tests.theTestName`. Just makes it easier when the next person adds additional tests for a definition.

**Comment by runarorama** [comment]
Made the requested changes, @pchiusano

**Comment by runarorama** [comment]
OK, made all the changes we talked about, for real this time.

**Comment by pchiusano** [comment]
Great, merged in namespace hash #7hg8ta6vg4

**Comment by pchiusano** [comment]
@runarorama I updated the testing docs as well on the site, will go live with this release

**Comment by runarorama** [comment]
It's almost like we should make the docs `Doc` objects.

**Comment by aryairani** [comment]
I was recently thinking the same.  Who wants to take the lead on planning this?
