### ISSUE TITLE
Add `Set.unions` and `Set.flatten` and necessary dependencies

### ISSUE THREAD

**Issue by runarorama** [unisonweb/base_v1#28]
This adds `Set.unions` and `Set.flatten`, along with their missing dependencies.

## Code review

  The changes summarized below are available for you to review, using the
  following command:

    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/runarorama/mybase:.prs._pr28

  Added definitions:

     Int.decrement                 : Int -> Int (+3 metadata)
     Int.decrement.doc             : Doc (+2 metadata)
     Int.decrement.test            : [Result] (+3 metadata)
     List.foldr                    : (a ->{e} b ->{e} b)
                                   -> b
                                   -> [a]
                                   ->{e} b (+3 metadata)
     List.foldr.doc                : Doc (+2 metadata)
     List.foldr.tests.homomorphism : [Result] (+3 metadata)
     Nat.decrement                 : Nat -> Nat (+3 metadata)
     Nat.decrement.doc             : Doc (+2 metadata)
     Nat.decrement.test            : [Result] (+3 metadata)
     Set.flatMap                   : (a ->{e} Set b)
                                   -> Set a
                                   ->{e} Set b (+3 metadata)
     Set.flatMap.doc               : Doc (+2 metadata)
     Set.flatMap.tests.associative : [Result] (+3 metadata)
     Set.flatMap.tests.unit        : [Result] (+3 metadata)
     Set.flatten                   : Set (Set b) -> Set b (+3 metadata)
     Set.flatten.doc               : Doc (+2 metadata)
     Set.flatten.tests.associative : [Result] (+3 metadata)
     Set.flatten.tests.unit        : [Result] (+3 metadata)
     Set.foldl                     : (b ->{e} a ->{e} b)
                                   -> b
                                   -> Set a
                                   ->{e} b (+3 metadata)
     Set.foldl.doc                 : Doc (+2 metadata)
     Set.foldl.tests.homomorphism  : [Result] (+3 metadata)
     Set.foldr                     : (a ->{e} b ->{e} b)
                                   -> b
                                   -> Set a
                                   ->{e} b (+3 metadata)
     Set.foldr.doc                 : Doc (+2 metadata)
     Set.foldr.tests.homomorphism  : [Result] (+3 metadata)
     Set.unions                    : [Set a] -> Set a (+3 metadata)
     Set.unions.doc                : Doc (+2 metadata)
     Set.unions.test               : [Result] (+3 metadata)

**Comment by pchiusano** [comment]
LGTM, merged in namespace hash #1b50uit548
