### ISSUE TITLE
Add `List.head`

### ISSUE THREAD

**Issue by runarorama** [unisonweb/base_v1#32]
The changes summarized below are available for you to review, using the following command:

    pull-request.load https://github.com/unisonweb/base:.trunk.List https://github.com/runarorama/berlinfp

  Added definitions:

     head                           : [a] -> Optional a (+1 metadata)
     head.doc                       : Doc
     head.examples.evaluated.elems  : Optional Nat
     head.examples.evaluated.empty  : Optional a
     head.examples.evaluated.single : Optional Nat
     head.test                      : [Result] (+1 metadata)

**Comment by pchiusano** [comment]
Merged in namespace hash #3dbjkfbh29

This was missing author and license info for some reason... I just added it when doing the merge, but it's a bit tedious having to do that. :)
