### ISSUE TITLE
contributing guidelines don't acknowledge trunk or PR namespace

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base_v1#33]
I think that [CONTRIBUTING.md](https://github.com/unisonweb/base/blob/211c8de79313ca1cf4c3edebae840e151b3befcc/CONTRIBUTING.md) might be in need of updating. It doesn't seem to reflect that `base` now follows a `trunk` namespace convention. It also doesn't seem to follow the suggestions of making changes in a `.pr._myFeature` namespace.

This is an issue and not a PR because I'm not sure that I understand the proper way to do things yet. I've mucked things up a few times trying to figure out where I need to add `:.prs._myFeature` in the various `push`, `pull`, and `pull-request.create` commands.

**Comment by pchiusano** [comment]
Thanks! Lemme see about updating it.

**Comment by pchiusano** [comment]
Okay, took a crack at it. LMK what you think.

**Comment by ceedubs** [comment]
Thanks @pchiusano this is really helpful. In fact, I think that this might be a bit easier to follow than the docs on creating a PR that it links to; that doc seems to go in and out of using `trunk` and `pr`namespaces, and the section on updating to the latest trunk comes after the section on creating a PR. I was planning on opening up issues/PRs for that doc as I came to understand the Unison workflow. Hopefully I'm in a better position to do that now that you've made this change.

Given that the contributing guidelines are intended for new contributors, I think that they still suffer from [this issue](https://github.com/unisonweb/unison/issues/1492), but since there's already an issue for that one, I'll close this one out.

**Comment by aryairani** [comment]
@pchiusano New guide looks great!

> Tests and docs can't go under operators

Would you check for me if this is true in M1jkl?  I have a vague suspicion that it isn’t.

**Comment by pchiusano** [comment]
Cool, glad it was helpful!

I think the docs on the site need a lot of work and could be simplified, sorry about the complexity there.

**Comment by ceedubs** [comment]
@pchiusano I noticed that in these contributing guidelines you pull `base.trunk` into `_base` instead of into `_base.trunk`. Is that your typical workflow? It seems to vary slightly from the docs on [codebase organization](https://www.unisonweb.org/docs/codebase-organization/) in the "If you're including multiple projects in the same Unison codebase" section.
