### ISSUE TITLE
Add test.gen.Gen.either

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base_v1#34]
**Disclaimer: I have no idea what I'm doing.**

Before submitting a pull request, please doublecheck that you have included

[x] a clear PR description (don't bother to include issues numbers).
[x] `Doc`s linked for types and terms as needed
[ ] `Author` and `License` metadata linked
    I've added author metadata, but I'm not sure that I did it right. Afterwards I saw that the contributing guidelines said that someone would do this for me when I opened my PR, so I held off on adding licensing info.
[x] `Test`s, where appropriate

This PR adds `test.gen.Gen.either`:

```
> view test.gen.Gen.either

  test.gen.Gen.either : '{Gen} a -> '{Gen} b -> '{Gen} Either a b
  test.gen.Gen.either a b = pick ['(Left !a), '(Right !b)]
```

```
> docs test.gen.Gen.either

  
  Given the ability to generate values of type `a` and the ability to generate values of type `b`, generate
  `Either a b` values, alternating between `Left a` and `Right b`.
```

## Code review
  The changes summarized below are available for you to review, using the following command:
  
    pull-request.load git@github.com:unisonweb/base:.trunk git@github.com:ceedubs/unison-base:.prs._genEither
  
  Added definitions:
  
     metadata.authors.ceedubs          : Author
     metadata.authors.ceedubs.guid     : GUID
     metadata.copyrightHolders.ceedubs : CopyrightHolder
     test.gen.Gen.either               : '{Gen} a -> '{Gen} b -> '{Gen} Either a b (+2 metadata)
     test.gen.Gen.either.doc           : Doc
     test.gen.Gen.either.test          : [Result] (+2 metadata)

**Comment by ceedubs** [comment]
Oh this namespace is probably wrong. I was thinking that most of the `Gen` stuff was in `test.gen.Gen` but it looks like it's just `test.gen`. I'm not sure if things have shifted around since I first started on this or I just misread in the first place.

If this is something that you'd like to have in base, what do you think that the fully-qualified name for this should be? `test.gen.either`? It's pretty similar to `test.pairOf`, but it looks like that method is an exception to the rule that `Gen` methods are in the `test.gen` namespace.

**Comment by runarorama** [comment]
For the licensing, just add the following to your PR, for example if you want to release these under the MIT license:

```
metadata.licenses.ceedubs2020 = License [ceedubs] [Year 2020] mit
```

Alternatively, I can do this for you if you just comment here that you'd like me to do that and that this code is in fact MIT licensed.

**Comment by ceedubs** [comment]
Thanks @runarorama I'll give it a try. Should I also move this to `test.gen.either` instead of `test.gen.Gen.either`?

**Comment by ceedubs** [comment]
@runarorama okay I took the liberty of using `test.gen.either` instead of `test.gen.Gen.either`; let me know if I should revert that change.

```
.prs._genEither> diff.namespace ._base .prs._genEither

  Added definitions:
  
    1. metadata.authors.ceedubs          : Author
    2. metadata.authors.ceedubs.guid     : GUID
    3. metadata.copyrightHolders.ceedubs : CopyrightHolder
    4. metadata.licences.ceedubs2020     : License
    5. test.gen.either                   : '{Gen} a -> '{Gen} b -> '{Gen} Either a b (+3 metadata)
    6. test.gen.either.doc               : Doc (+1 metadata)
    7. test.gen.either.test              : [Result] (+3 metadata)
```

My diff was showing that I removed `List.head` and I couldn't seem to get `patch` to do what I wanted, so I ended up doing a `merge` from `_base`. With this, and moving the namespace for `either`, the git history is probably a bit messy. Is that a concern? Is rebasing a thing in Unison?

**Comment by runarorama** [comment]
Looks good!

As a general comment, don't worry about picking the perfect names for things, as moving things around later is a trivial and non-breaking change.

**Comment by runarorama** [comment]
Regarding the history, what I will probably do is make a fresh `fork base foo` and alias all your definitions into `foo`, then push that to GH.

**Comment by ceedubs** [comment]
@runarorama thanks! If you'd be willing to paste the ucm input (and maybe output?) from when you do that, I'd find that useful.

**Comment by runarorama** [comment]
Great idea! Here's a gist of what I did:

https://gist.github.com/runarorama/3f80771ca44492889fed04c4e33a26b2

**Comment by ceedubs** [comment]
@runarorama thanks again; very helpful.

Out of curiosity, why did you delete the test for `gen.either`?

**Comment by runarorama** [comment]
Thanks for this PR @ceedubs! Merged in base hash #pr0nnfjg3q. 🦄 🌈 🎠 

I added authorship information for your `Doc` object, and deleted your test. The reason I deleted the test is that it depends heavily on the implementations of `pick` and `sample`, which might change in the future.

The test was helpful, as it showed that your generator is correct. But now that we know that, keeping the test around isn't buying us anything.

**Comment by runarorama** [comment]
It occurs to me that somebody should really make `gen.optional` as well.

**Comment by ceedubs** [comment]
@runarorama I think that I have an implementation of that sitting in a scratch file somewhere. I'll give a go at turning it into another PR in the next few days.

**Comment by ceedubs** [comment]
#51 is currently holding me up on `gen.optional`.
