### ISSUE TITLE
a few functions: inRange/max/min, xor, all/any/none, iterate/until

### ISSUE THREAD

**Issue by atacratic** [unisonweb/base_v1#35]
A few functions for `base`, written in passing as I was working on PRNG stuff.

## Things to highlight
- the function I'm proposing to call `iterate` has a different signature from the haskell function of the same name (and from Runar's function in his lib https://github.com/runarorama/unisonlibraries)
   - Haskell has `(a -> a) -> a -> [a]`
   - Runar has `Nat -> (a ->{𝕖} a) -> a ->{𝕖} [a]`
   - I have `Nat -> '{e} a ->{e} [a]`
- I'm proposing to give my `(a ->{e} Boolean) -> '{e} a ->{e} a` the name `until`
- the inRange functions are inclusive on the left but exclusive on the right

## Code review

```
  The changes summarized below are available for you to review, using the following command:
  
    pull-request.load https://github.com/unisonweb/base https://github.com/atacratic/unisonweb-base
  
  Added definitions:
  
     Int.inRange                          : Int -> Int -> Int -> Boolean (+3 metadata)
     Int.inRange.doc                      : Doc (+2 metadata)
     Int.max                              : Int -> Int -> Int (+2 metadata)
     Int.min                              : Int -> Int -> Int (+2 metadata)
     List.all                             : (a ->{𝕖} Boolean) ->{𝕖} [a] ->{𝕖} Boolean (+2 metadata)
     List.any                             : (a ->{𝕖} Boolean) ->{𝕖} [a] ->{𝕖} Boolean (+2 metadata)
     List.none                            : (a ->{𝕖} Boolean) ->{𝕖} [a] ->{𝕖} Boolean (+2 metadata)
     Nat.inRange                          : Nat -> Nat -> Nat -> Boolean (+3 metadata)
     Nat.inRange.doc                      : Doc (+2 metadata)
     Nat.max                              : Nat -> Nat -> Nat (+2 metadata)
     Nat.min                              : Nat -> Nat -> Nat (+2 metadata)
     iterate                              : Nat -> '{e} a ->{e} [a] (+3 metadata)
     iterate.doc                          : Doc (+2 metadata)
     iterate.test                         : [Result] (+3 metadata)
     metadata.authors.atacratic           : Author
     metadata.authors.atacratic.guid      : GUID
     metadata.copyrightHolders.atacratic  : CopyrightHolder
     metadata.licenses.atacratic.mit_2020 : License
     until                                : (a ->{e} Boolean) -> '{e} a ->{e} a (+3 metadata)
     until.doc                            : Doc (+2 metadata)
     xor                                  : Boolean -> Boolean -> Boolean (+3 metadata)
     xor.doc                              : Doc (+2 metadata)
     xor.test                             : [Result] (+3 metadata)
  
     patch patch (added 1 updates)
     patch patches.dev (added 3 updates)
  
  Name changes:
  
    Original                                                       Changes
     releases._M1j.Abort                                        ┐   Abort (added)
     releases._M1k.Abort                                        │  
     releases._M1l.Abort                                        │  
     releases._latest.Abort                                     │  
     trunk.Abort                                                ┘  
    
     releases._M1j.Ask                                          ┐   Ask (added)
     releases._M1k.Ask                                          │  
     releases._M1l.Ask                                          │  
     releases._latest.Ask                                       │  
     trunk.Ask                                                  ┘  

...    

```

... and lots more name changes like that.  Is this fishy?  

Also not sure why it's flagging patch changes - the two patches don't contain anything related to my additions.

**Comment by pchiusano** [comment]
@atacratic Cool!!

It looks like your PR is merging what seems to be a copy of `trunk` into the root namespace of this repo, which probably isn't what you want (the only thing under the root namespace of this repo should be like `trunk` and `releases`). 

I just updated the [contributing docs](https://github.com/unisonweb/base/blob/master/CONTRIBUTING.md) which I think has clearer instructions.

If your repo is a copy of `trunk`, I think the command might be:

```
.> pull-request.create https://github.com/unisonweb/base:.trunk https://github.com/atacratic/unisonweb-base
```

In Haskell,  your version `iterate` would be called `replicateM` I guess, and "iterating" is usually for "iterating a function". I'd probably go with `List.replicate!` but maybe we'll revisit that later (no big deal!!). `until` seems okay to me.

**Comment by atacratic** [comment]
@pchiusano OK how about this? :smile: 

```
  The changes summarized below are available for you to review, using the following
  command:
  
    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/atacratic/unison-playpen:.temp.base
  
  Added definitions:
  
  
     Int.inRange                          : Int -> Int -> Int -> Boolean (+3 metadata)
     Int.inRange.doc                      : Doc (+2 metadata)
     Int.inRange.max                      : Int -> Int -> Int (+2 metadata)
     Int.inRange.min                      : Int -> Int -> Int (+2 metadata)
     List.all                             : (a ->{𝕖} Boolean)
                                          ->{𝕖} [a]
                                          ->{𝕖} Boolean (+2 metadata)
     List.any                             : (a ->{𝕖} Boolean)
                                          ->{𝕖} [a]
                                          ->{𝕖} Boolean (+2 metadata)
     List.none                            : (a ->{𝕖} Boolean)
                                          ->{𝕖} [a]
                                          ->{𝕖} Boolean (+2 metadata)
     Nat.inRange                          : Nat -> Nat -> Nat -> Boolean (+3 metadata)
     Nat.inRange.doc                      : Doc (+2 metadata)
     Nat.max                              : Nat -> Nat -> Nat (+2 metadata)
     Nat.min                              : Nat -> Nat -> Nat (+2 metadata)
     metadata.authors.atacratic           : Author
     metadata.authors.atacratic.guid      : GUID
     metadata.copyrightHolders.atacratic  : CopyrightHolder
     metadata.licenses.atacratic.mit_2020 : License
     replicate                            : Nat -> '{e} a ->{e} [a] (+3 metadata)
     replicate.doc                        : Doc (+2 metadata)
     replicate.test                       : [Result] (+3 metadata)
     until                                : (a ->{e} Boolean)
                                          -> '{e} a
                                          ->{e} a (+3 metadata)
     until.doc                            : Doc (+2 metadata)
     xor                                  : Boolean -> Boolean -> Boolean (+3 metadata)
     xor.doc                              : Doc (+2 metadata)
     xor.test                             : [Result] (+3 metadata)
```

**Comment by pchiusano** [comment]
@atacratic looks much better :) A couple minor things which I didn't spot in first pass. I don't mind fixing these up during the merge if you prefer.

1. Can you add a manual annotation to List.all/any/none, they should be pure after receiving their first argument but due to https://github.com/unisonweb/unison/issues/1185 they are getting the same `{e}` requirement there.
2. Move `replicate` into `List` namespace.

**Comment by atacratic** [comment]
@pchiusano thanks - here it is!

```
  The changes summarized below are available for you to review, using the following command:
  
    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/atacratic/unison-playpen:.temp.base
  
  Added definitions:
  
     Int.inRange                          : Int -> Int -> Int -> Boolean (+3 metadata)
     Int.inRange.doc                      : Doc (+2 metadata)
     Int.inRange.max                      : Int -> Int -> Int (+2 metadata)
     Int.inRange.min                      : Int -> Int -> Int (+2 metadata)
     List.all                             : (a ->{e} Boolean) -> [a] ->{e} Boolean (+2 metadata)
     List.any                             : (a ->{e} Boolean) -> [a] ->{e} Boolean (+2 metadata)
     List.none                            : (i ->{e} Boolean) -> [i] ->{e} Boolean (+3 metadata)
     List.replicate                       : Nat -> '{e} a ->{e} [a] (+3 metadata)
     List.replicate.doc                   : Doc (+2 metadata)
     List.replicate.test                  : [Result] (+3 metadata)
     Nat.inRange                          : Nat -> Nat -> Nat -> Boolean (+3 metadata)
     Nat.inRange.doc                      : Doc (+2 metadata)
     Nat.max                              : Nat -> Nat -> Nat (+2 metadata)
     Nat.min                              : Nat -> Nat -> Nat (+2 metadata)
     metadata.authors.atacratic           : Author
     metadata.authors.atacratic.guid      : GUID
     metadata.copyrightHolders.atacratic  : CopyrightHolder
     metadata.licenses.atacratic.mit_2020 : License
     until                                : (a ->{e} Boolean) -> '{e} a ->{e} a (+3 metadata)
     until.doc                            : Doc (+2 metadata)
     xor                                  : Boolean -> Boolean -> Boolean (+3 metadata)
     xor.doc                              : Doc (+2 metadata)
     xor.test                             : [Result] (+3 metadata)

```

**Comment by pchiusano** [comment]
Looks great! I’ll merge when I’m at a computer next.

**Comment by runarorama** [comment]
A minor niggle with the doc for `xor`: exclusive-or actually can't be short-circuiting, since you need both arguments to know the result. But maybe it's fine to call this out explicitly, as you have.

**Comment by runarorama** [comment]
Why are `min` and `max` for `Int` under `inRange`?

**Comment by runarorama** [comment]
`min` and `max` for both `Int` and `Nat` could use docs, as could `all`, `any`, and `none` for `List`.

All of these could use at least one test.

**Comment by atacratic** [comment]
OK, done all that :smile: 

```
  The changes summarized below are available for you to review, using the following command:
  
    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/atacratic/unison-playpen:.temp.base
  
  Added definitions:
  
     Int.inRange                          : Int -> Int -> Int -> Boolean (+3 metadata)
     Int.inRange.doc                      : Doc (+2 metadata)
     Int.inRange.test1                    : [Result] (+3 metadata)
     Int.inRange.test2                    : [Result] (+3 metadata)
     Int.inRange.test3                    : [Result] (+3 metadata)
     Int.inRange.test4                    : [Result] (+3 metadata)
     Int.inRange.test5                    : [Result] (+3 metadata)
     Int.max                              : Int -> Int -> Int (+3 metadata)
     Int.max.doc                          : Doc (+2 metadata)
     Int.max.test1                        : [Result] (+3 metadata)
     Int.max.test2                        : [Result] (+3 metadata)
     Int.min                              : Int -> Int -> Int (+3 metadata)
     Int.min.doc                          : Doc (+2 metadata)
     Int.min.test1                        : [Result] (+3 metadata)
     Int.min.test2                        : [Result] (+3 metadata)
     List.all                             : (a ->{e} Boolean) -> [a] ->{e} Boolean (+3 metadata)
     List.all.doc                         : Doc (+2 metadata)
     List.all.test1                       : [Result] (+3 metadata)
     List.all.test2                       : [Result] (+3 metadata)
     List.all.test3                       : [Result] (+3 metadata)
     List.any                             : (a ->{e} Boolean) -> [a] ->{e} Boolean (+3 metadata)
     List.any.doc                         : Doc (+2 metadata)
     List.any.test1                       : [Result] (+3 metadata)
     List.any.test2                       : [Result] (+3 metadata)
     List.any.test3                       : [Result] (+3 metadata)
     List.none                            : (i ->{e} Boolean) -> [i] ->{e} Boolean (+4 metadata)
     List.none.doc                        : Doc (+2 metadata)
     List.none.test1                      : [Result] (+3 metadata)
     List.none.test2                      : [Result] (+3 metadata)
     List.none.test3                      : [Result] (+3 metadata)
     List.replicate                       : Nat -> '{e} a ->{e} [a] (+3 metadata)
     List.replicate.doc                   : Doc (+2 metadata)
     List.replicate.test                  : [Result] (+3 metadata)
     Nat.inRange                          : Nat -> Nat -> Nat -> Boolean (+3 metadata)
     Nat.inRange.doc                      : Doc (+2 metadata)
     Nat.inRange.test1                    : [Result] (+3 metadata)
     Nat.inRange.test2                    : [Result] (+3 metadata)
     Nat.inRange.test3                    : [Result] (+3 metadata)
     Nat.inRange.test4                    : [Result] (+3 metadata)
     Nat.inRange.test5                    : [Result] (+3 metadata)
     Nat.max                              : Nat -> Nat -> Nat (+3 metadata)
     Nat.max.doc                          : Doc (+2 metadata)
     Nat.max.test1                        : [Result] (+3 metadata)
     Nat.max.test2                        : [Result] (+3 metadata)
     Nat.min                              : Nat -> Nat -> Nat (+3 metadata)
     Nat.min.doc                          : Doc (+2 metadata)
     Nat.min.test1                        : [Result] (+3 metadata)
     Nat.min.test2                        : [Result] (+3 metadata)
     metadata.authors.atacratic           : Author (+2 metadata)
     metadata.authors.atacratic.guid      : GUID (+2 metadata)
     metadata.copyrightHolders.atacratic  : CopyrightHolder (+2 metadata)
     metadata.licenses.atacratic.mit_2020 : License (+2 metadata)
     until                                : (a ->{e} Boolean) -> '{e} a ->{e} a (+3 metadata)
     until.doc                            : Doc (+2 metadata)
     until.test                           : [Result] (+3 metadata)
     xor                                  : Boolean -> Boolean -> Boolean (+3 metadata)
     xor.doc                              : Doc (+2 metadata)
     xor.test                             : [Result] (+3 metadata)

```

If the bar for new additions to base is actually now 'tests and docs for everything`, it would be good to say that in CONTRIBUTING.md, to avoid mismatched expectations / contributor frustrations.

**Comment by runarorama** [comment]
That's a fair point, will definitely update CONTRIBUTING.md, as we want to encourage docs and tests in base.

**Comment by pchiusano** [comment]
👍 one more super minor thing which one of us will fix up on merge (because we’ve already subjected you to too much back and forth 😀) is name your tests like xor.tests.someName or if you are feeling uncreative, xor.tests.{t1,t2,prop1,prop2}. 

Under each namespace there can be a tests namespace, an examples namespace (often linked to by docs), a docs namespace (for supporting / not the main docs), and probably other categories of stuff later.

**Comment by runarorama** [comment]
I'm on it.

**Comment by runarorama** [comment]
OK, I actually ended up completely rewriting these tests rather than just moving them around. 😄 

I'm hoping to model what I think excellent tests should look like.

Please take a look. @pchiusano can merge if everything looks OK. In particular, I am not sure what the patch diff means here, as there is not a patch in `base.trunk`, nor in this PR.


  The changes summarized below are available for you to review, using the
  following command:

    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/runarorama/mybase:.atacratic35

  Updates:

     patch patch (deleted 0 updates)

  Added definitions:

     Boolean.xor                          : Boolean
                                          -> Boolean
                                          -> Boolean (+3 metadata)
     Boolean.xor.doc                      : Doc (+2 metadata)
     Boolean.xor.test                     : [Result] (+3 metadata)
     Int.inRange                          : Int
                                          -> Int
                                          -> Int
                                          -> Boolean (+3 metadata)
     Int.inRange.doc                      : Doc (+2 metadata)
     Int.inRange.test                     : [Result] (+3 metadata)
     Int.max                              : Int -> Int -> Int (+3 metadata)
     Int.max.doc                          : Doc (+2 metadata)
     ┌ Int.max.tests.absorption           : [Result] (+3 metadata)
     └ Int.min.tests.absorption           : [Result] (+3 metadata)
     Int.max.tests.associative            : [Result] (+3 metadata)
     Int.max.tests.commutative            : [Result] (+3 metadata)
     Int.max.tests.deMorgan               : [Result] (+3 metadata)
     Int.max.tests.distributesOverMin     : [Result] (+3 metadata)
     Int.max.tests.idempotent             : [Result] (+3 metadata)
     Int.max.tests.partialOrder           : [Result] (+3 metadata)
     Int.max.tests.top                    : [Result] (+3 metadata)
     Int.min                              : Int -> Int -> Int (+3 metadata)
     Int.min.doc                          : Doc (+2 metadata)
     Int.min.tests.associative            : [Result] (+3 metadata)
     Int.min.tests.bottom                 : [Result] (+3 metadata)
     Int.min.tests.commutative            : [Result] (+3 metadata)
     Int.min.tests.deMorgan               : [Result] (+3 metadata)
     Int.min.tests.distributesOverMax     : [Result] (+3 metadata)
     Int.min.tests.idempotent             : [Result] (+3 metadata)
     Int.min.tests.partialOrder           : [Result] (+3 metadata)
     List.all                             : (a ->{e} Boolean)
                                          -> [a]
                                          ->{e} Boolean (+3 metadata)
     List.all.doc                         : Doc (+2 metadata)
     List.all.tests.deMorgan              : [Result] (+3 metadata)
     List.all.tests.homomorphism          : [Result] (+3 metadata)
     List.any                             : (a ->{e} Boolean)
                                          -> [a]
                                          ->{e} Boolean (+3 metadata)
     List.any.doc                         : Doc (+2 metadata)
     List.any.tests.deMorgan              : [Result] (+3 metadata)
     List.any.tests.homomorphism          : [Result] (+3 metadata)
     List.none                            : (i ->{e} Boolean)
                                          -> [i]
                                          ->{e} Boolean (+4 metadata)
     List.none.doc                        : Doc (+2 metadata)
     List.replicate                       : Nat -> '{e} a ->{e} [a] (+3 metadata)
     List.replicate.doc                   : Doc (+2 metadata)
     List.replicate.test                  : [Result] (+3 metadata)
     List.replicate.test.doc              : Doc (+2 metadata)
     Nat.inRange                          : Nat
                                          -> Nat
                                          -> Nat
                                          -> Boolean (+3 metadata)
     Nat.inRange.doc                      : Doc (+2 metadata)
     Nat.inRange.test                     : [Result] (+3 metadata)
     Nat.max                              : Nat -> Nat -> Nat (+3 metadata)
     Nat.max.doc                          : Doc (+2 metadata)
     Nat.max.tests.absorption             : [Result] (+3 metadata)
     Nat.max.tests.additionDistributes    : [Result] (+3 metadata)
     Nat.max.tests.associative            : [Result] (+3 metadata)
     Nat.max.tests.commutative            : [Result] (+3 metadata)
     Nat.max.tests.distributesOverMin     : [Result] (+3 metadata)
     Nat.max.tests.idempotent             : [Result] (+3 metadata)
     Nat.max.tests.identity               : [Result] (+3 metadata)
     Nat.max.tests.partialOrder           : [Result] (+3 metadata)
     ┌ Nat.max.tests.summation            : [Result] (+3 metadata)
     └ Nat.min.tests.summation            : [Result] (+3 metadata)
     Nat.min                              : Nat -> Nat -> Nat (+3 metadata)
     Nat.min.doc                          : Doc (+2 metadata)
     Nat.min.tests.additionDistributes    : [Result] (+3 metadata)
     Nat.min.tests.associative            : [Result] (+3 metadata)
     Nat.min.tests.commutative            : [Result] (+3 metadata)
     Nat.min.tests.distributesOverMax     : [Result] (+3 metadata)
     Nat.min.tests.idempotent             : [Result] (+3 metadata)
     Nat.min.tests.identity               : [Result] (+3 metadata)
     Nat.min.tests.partialOrder           : [Result] (+3 metadata)
     Universal.!=                         : a -> a -> Boolean (+2 metadata)
     Weighted.ints                        : Weighted Int (+2 metadata)
     metadata.authors.atacratic           : Author (+2 metadata)
     metadata.authors.atacratic.guid      : GUID (+2 metadata)
     metadata.copyrightHolders.atacratic  : CopyrightHolder (+2 metadata)
     metadata.licenses.atacratic.mit_2020 : License (+2 metadata)
     test.boolean                         : '{Gen} Boolean (+3 metadata)
     test.boolean.doc                     : Doc (+2 metadata)
     test.int                             : '{Gen} Int (+2 metadata)
     test.laws.absorption                 : '{Gen} a
                                          -> (a ->{Gen} a ->{Gen} a)
                                          -> (a ->{Gen} a ->{Gen} a)
                                          ->{Gen} Test (+3 metadata)
     test.laws.absorption.doc             : Doc (+2 metadata)
     test.laws.associative                : '{Gen} a
                                          -> (a ->{Gen} a ->{Gen} a)
                                          ->{Gen} Test (+3 metadata)
     test.laws.associative.doc            : Doc (+2 metadata)
     test.laws.commutative                : '{Gen} a
                                          -> (a ->{Gen} a ->{Gen} b)
                                          ->{Gen} Test (+3 metadata)
     test.laws.commutative.doc            : Doc (+2 metadata)
     test.laws.distributive               : '{Gen} a
                                          -> (a ->{Gen} a ->{Gen} a)
                                          -> (a ->{Gen} a ->{Gen} a)
                                          ->{Gen} Test (+3 metadata)
     test.laws.distributive.doc           : Doc (+2 metadata)
     test.laws.homomorphism               : '{Gen} a
                                          -> (a ->{Gen} b)
                                          -> (a ->{Gen} a ->{Gen} a)
                                          -> (b ->{Gen} b ->{Gen} b)
                                          ->{Gen} Test (+3 metadata)
     test.laws.homomorphism.doc           : Doc (+2 metadata)
     test.laws.idempotence                : '{Gen} a
                                          -> (a ->{Gen} a ->{Gen} a)
                                          ->{Gen} Test (+3 metadata)
     test.laws.idempotence.doc            : Doc (+2 metadata)
     until                                : (a ->{e} Boolean)
                                          -> '{e} a
                                          ->{e} a (+3 metadata)
     until.doc                            : Doc (+2 metadata)
     until.test                           : [Result] (+5 metadata)

**Comment by atacratic** [comment]
This is all good stuff.  My only worry is that if we're actually requiring property tests for a maximal suite of algebraic laws, even for trivial one-liners like `Nat.min`, then we will end up with noone contributing functions like that.  

It also seems a bit overkill to do before typeclasses - if these were laws on a `Num` typeclass then I'd say great, as they communicate assumptions and guarantees about future implementations. As it is it's a heck of a lot of names in the namespace for not much testing value.

**Comment by atacratic** [comment]
The more I think about this the more it seems to be an instance of "it's going to be a pain sometimes to add stuff to base without having (Unison's take on) typeclasses implemented yet".  We'll often need to choose between (a) trying to get the same effect in a more painful way and (b) not bothering for now.

Maybe the typeclass language design decision will end up being "Unison's take on bounded polymorphism will use implicit parameters to pass dictionaries as records".

If so, would there be any sense in starting to build out base and other libraries using the explicit encoding now, in the absence of the language feature, in the knowledge we can easily sugar it up by coming back and making some parameters implicit later?

For that we'd need a decision on the approach to typeclasses, some confidence that switching encoding later will be feasible, and some documentation of the encoding and naming idioms.  Is it worth trying to get those things soon, as part of creating the right environment for Unison's library ecosystem to start to grow?

FWIW here's my take on what the explicit encoding could look like for testing algebraic properties: [sketch gist](https://gist.github.com/atacratic/65b7eae9fb397f6bc68752955bd81ad9).  I can imagine myself contributing code that looks like this, because the footprint on each instance is just one simple definition with high power-to-weight ratio, it doesn't involve creating reams of repetitive names, and because it's working at the level of the actual abstractions involved (Monoid in this example) rather than their constituent laws.

**Comment by runarorama** [comment]
I don't think we're going to require property tests like this for every pull request that comes in. Your tests were probably fine to merge as they were, but I wanted to model what checking the properties of these kinds of algebraic operations would be like.

I think type classes are somewhat orthogonal to this kind of testing. We can check algebraic laws of common operations without necessarily having type classes for those algebras.

You make a good point about namespace explosion, so maybe it would be better if e.g. `Int.max` just had one test named `distributiveLattice` which completely specifies its behaviour. That said, base is going to have a lot of names in it and we probably need to handle that well.

**Comment by runarorama** [comment]
@pchiusano merge when ready.

Pay attention to the `patch patch (deleted 0 updates)` bit. I am not sure what that's about.

**Comment by pchiusano** [comment]
Cool. I can’t get to it today but will do tomorrow.

**Comment by runarorama** [comment]
Thanks @atacratic!

Merged in base hash #nea65tdhgk.

🦾

**Comment by runarorama** [comment]
Since we have `xor`, for completeness it would be nice to also have `implies` (material implication) and `given` (inverse implication).

Same with `until`. It would be cool to have `while` as well (so we can have while-loops!)
