### ISSUE TITLE
Adds List.intersperse

### ISSUE THREAD

**Issue by dariooddenino** [unisonweb/base_v1#36]
This pull request adds List.intersperse. Hope everything's fine!

## Code review

The changes summarized below are available for you to review, using the following command:
  
    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/dariooddenino/unisoncode:.prs.base._intersperse
  
  Updates:
  
     patch patch (added 1 updates)
  
  Added definitions:
  
     List.intersperse                             : a -> [a] -> [a] (+1 metadata)
     List.intersperse.doc                         : Doc
     List.intersperse.tests.base                  : [Result] (+1 metadata)
     List.intersperse.tests.empty                 : [Result] (+1 metadata)
     List.metadata.authors.dariooddenino          : Author
     List.metadata.authors.dariooddenino.guid     : GUID
     List.metadata.copyrightHolders.dariooddenino : CopyrightHolder
     metadata.authors.dariooddenino               : Author
     metadata.authors.dariooddenino.guid          : GUID
     metadata.copyrightHolders.dariooddenino      : CopyrightHolder
     metadata.licenses.dariooddenino2020          : License (+1 metadata)

**Comment by pchiusano** [comment]
Cool! Can you make sure you’ve set your default author and license? The diff only has one metadata linked for the new definitions.

Instructions here: https://github.com/unisonweb/base/blob/master/CONTRIBUTING.md

**Comment by dariooddenino** [comment]
Umm I followed that guide and I was hoping everything was good :( I'll try again once I figure out how

**Comment by dariooddenino** [comment]
I have added `DefaultMetadata = { prs.base = [".metadata.licenses.dariooddenino2020"] }` to my .unisonCofig , but either it doesn't work retroactively, or I messed something up. 

I then tried `link .metadata.licenses.dariooddenino2020 .prs.base._intersperse.List.intersperse`, which gave me what looked like a successful message, but when I check the diff with _base nothing changed from my pull request up here.

**Comment by pchiusano** [comment]
It’s not retroactive, though not sure why you’re not seeing any diff, unless it is already licensed.

I’ll take a look today. Could you just assign a license by commenting on this ticket. Just say “I hereby license the definitions listed in this PR using the MIT license” and then I can fix up during the merge. Thanks!

**Comment by dariooddenino** [comment]
I hereby license the definitions listed in this PR using the MIT license.

Sorry I wasn't able to fix it in the proper way :(

**Comment by runarorama** [comment]
Merged in base hash #si57j4rje9 🦄 🌈 🥇 . Thanks @dariooddenino !!
