### ISSUE TITLE
Add Substitution ability and the contravariant functor for functions

### ISSUE THREAD

**Issue by ghost** [unisonweb/base_v1#37]
Adds the ability to substitute one computation with another regardless of where you are in your current computation.

Inspired by the case study in chapter 7 of [this paper](https://dl.acm.org/doi/abs/10.1145/3331545.3342595).

This is basically an excuse to add `callCC` to unison.

Also includes the contravariant functor for `a -> r` while I was at it.

## Code review

  The changes summarized below are available for you to review, using the following command:

    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/bascott/codebase:.prs.base._add_substitution_ability

  Added definitions:

     type Comp r a (+2 metadata)
     ability Substitution ref (+2 metadata)
     Comp.Comp                           : (∀ e. a ->{e} r) -> Comp r a
     Substitution.jump                   : ref a -> a ->{Substitution ref} r (+3 metadata)
     Substitution.sub                    : {Substitution ref} (Either (ref a) a) (+3 metadata)
     Comp.<|                             : Comp r a -> a -> r (+2 metadata)
     Comp.contramap                      : (b -> a) -> Comp r a -> Comp r b (+2 metadata)
     Substitution.callCC                 : ((a ->{Substitution ref} b) ->{e} a)
                                         ->{e, Substitution ref} a (+3 metadata)
     Substitution.callCC.doc             : Doc (+2 metadata)
     Substitution.examples.ex1           : '{IO} () (+2 metadata)
     Substitution.jump.doc               : Doc (+2 metadata)
     Substitution.runComp                : '{e, Substitution (Comp r)} r ->{e} r (+2 metadata)
     Substitution.setjmp                 : a
                                         ->{Substitution ref} b
                                         ->{Substitution ref} r (+3 metadata)
     Substitution.setjmp.doc             : Doc (+2 metadata)
     Substitution.sub.doc                : Doc (+2 metadata)
     metadata.authors.bascott            : Author
     metadata.authors.bascott.guid       : GUID
     metadata.copyrightHolders.bascott   : CopyrightHolder
     metadata.licenses.bascott.bsd2_2020 : License
     metadata.licenses.bascott.bsd3_2020 : License
     metadata.licenses.bascott.mit_2020  : License

**Comment by pchiusano** [comment]
@bascott this looks very cool but I think belongs as a separate library. Want to create one and we can link it here? https://unisonweb.org/docs/libraries

**Comment by pchiusano** [comment]
Going to close but hope you will post your library!

**Comment by ghost** [comment]
@pchiusano Ok, I'll publish it on my own repo and link it in that document. Thanks for pointing me to there.
