### ISSUE TITLE
Add `List.concat`, `List.concatMap` and `List.filterMap`

### ISSUE THREAD

**Issue by emiflake** [unisonweb/base_v1#38]
Hi! This is a small PR to see if I got everything right. Here are some simple List functions that are missing.

----

  The changes summarized below are available for you to review, using the following command:

    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/emiflake/unison-emi.git:.prs.base._list_functions

  Added definitions:

     List.concat                                    : [[a]] -> [a] (+3 metadata)
     List.concat.doc                                : Doc (+2 metadata)
     List.concat.tests.ex1                          : [Result] (+3 metadata)
     List.concatMap                                 : (a ->{𝕖} [b]) -> [a] ->{𝕖} [b] (+3 metadata)
     List.concatMap.doc                             : Doc (+2 metadata)
     List.concatMap.tests.concatMapIdentityIsConcat : [Result] (+3 metadata)
     List.concatMap.tests.ex1                       : [Result] (+3 metadata)
     List.concatMap.tests.ex2                       : [Result] (+3 metadata)
     List.filterMap                                 : (a ->{𝕖} Optional b)
                                                    -> [a]
                                                    ->{𝕖} [b] (+3 metadata)
     List.filterMap.doc                             : Doc (+2 metadata)
     List.filterMap.tests.ex1                       : [Result] (+3 metadata)
     metadata.authors.emiflake                      : Author
     metadata.authors.emiflake.guid                 : GUID
     metadata.copyrightHolders.emiflake             : CopyrightHolder
     metadata.licenses.emiflake_mit_2020            : License (+1 metadata)

**Comment by runarorama** [comment]
Hi Emily,

Thanks for this! Just a couple of things to note:

`List.concat` exists already as `List.join`, and `List.concatMap` exists as `List.flatMap` although your implementation is better than the existing one.

Looks good otherwise, and thanks for adding tests and docs. I find it interesting that you basically invented "doctests" here.

Will merge.

**Comment by emiflake** [comment]
Oh dear! It probably did warn me be about `List.join` being the same as my `concat`, but since the implementation of `flatMap` was different, it couldn't tell me about that one. Whoops 🙂

**Comment by runarorama** [comment]
Yours uses `foldr` while the existing one uses `foldl`, so Unison wasn't able to nag you about it :)

**Comment by runarorama** [comment]
Merged in base.trunk hash #u86hp5f086

🌈
