### ISSUE TITLE
Add docs to `Tuple`

### ISSUE THREAD

**Issue by emiflake** [unisonweb/base_v1#41]
This PR adds some documentation to `Tuple`, `Tuple.at1`, `Tuple.at2`, `Tuple.at3`, and `Tuple.at4` as well as tests supporting the documentation.

`Tuple.doc` briefly explains the syntax sugar with tuples.

----

  The changes summarized below are available for you to review, using the following command:

    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/emiflake/unison-emi.git:.prs.base._tuple_docs

  Updates:

     type Tuple a b
       +  Tuple.doc : Doc

     Tuple.at1 : Tuple a b -> a
     +  at1.doc : Doc

     Tuple.at2 : Tuple a (Tuple b c) -> b
     +  at2.doc : Doc

     Tuple.at3 : Tuple a (Tuple b (Tuple c d)) -> c
     +  at3.doc : Doc

     Tuple.at4 : Tuple a (Tuple b (Tuple c (Tuple d e))) -> d
     +  at4.doc : Doc

     patch patch (added 1 updates)

  Added definitions:

     Tuple.at1.doc       : Doc (+2 metadata)
     Tuple.at1.tests.ex1 : [Result] (+3 metadata)
     Tuple.at2.doc       : Doc (+2 metadata)
     Tuple.at2.tests.ex1 : [Result] (+3 metadata)
     Tuple.at3.doc       : Doc (+2 metadata)
     Tuple.at3.tests.ex1 : [Result] (+3 metadata)
     Tuple.at3.tests.ex2 : [Result] (+3 metadata)
     Tuple.at4.doc       : Doc (+2 metadata)
     Tuple.at4.tests.ex1 : [Result] (+3 metadata)
     Tuple.at4.tests.ex2 : [Result] (+3 metadata)
     Tuple.doc           : Doc (+2 metadata)
     Tuple.tests.ex1     : [Result] (+2 metadata)
     Tuple.tests.ex2     : [Result] (+3 metadata)

**Comment by runarorama** [comment]
Merged in base hash #cleigmi48k. Thanks, @emiflake! 🌈🌟
