### ISSUE TITLE
Clean up the `test` namespace by putting generators in `gen`

### ISSUE THREAD

**Issue by runarorama** [unisonweb/base_v1#43]
This is a small change that only includes moving some names around for consistency and cleanup.

# Code review

  The changes summarized below are available for you to review, using the
  following command:

    pull-request.load https://github.com/unisonweb/base:.trunk.test https://github.com/runarorama/mybase:.genCleanup.test

  Name changes:

    Original        Changes
     boolean         gen.boolean (added)
                     boolean (removed)

     boolean.doc     gen.boolean.doc (added)
                     boolean.doc (removed)

     empty           gen.empty (added)
                     empty (removed)

     int             gen.int (added)
                     int (removed)

     listOf          gen.listOf (added)
                     listOf (removed)

     mapOf           gen.mapOf (added)
                     mapOf (removed)

     mapOf.doc       gen.mapOf.doc (added)
                     mapOf.doc (removed)

     nat             gen.nat (added)
                     nat (removed)

     natIn           gen.natIn (added)
                     natIn (removed)

     pairOf          gen.pairOf (added)
                     pairOf (removed)

     pairOf.doc      gen.pairOf.doc (added)
                     pairOf.doc (removed)

**Comment by pchiusano** [comment]
LGTM

**Comment by runarorama** [comment]
Merged in base hash #20fkqmrhbm.
