### ISSUE TITLE
Add Void and absurd

### ISSUE THREAD

**Issue by atacratic** [unisonweb/base_v1#44]
Adding 
```
type Void =

Void.doc = [: The uninhabited type.

No values of this type can be constructed, so it can be used for example 
to represent the return type of non-terminating computations. :]

absurd : Void -> a
absurd = cases
```

Umm, I temporarily hacked the parser in my ucm build to accept that empty 'cases' statement...  Alternative would be to use `bug` as per [this](https://app.slack.com/client/TLL09QC85/threads/thread/CLUNF0J5S-1588794031.211300).  I gave up trying to do a proper parser change to accept empty match/cases, and it'd be a very debatable change anyway.  

## Code review

  The changes summarized below are available for you to review, using the following command:
  
```
    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/atacratic/unison-playpen:._base.prs._1
  
  Added definitions:
  
     type Void (+3 metadata)
     Void.doc : Doc (+2 metadata)
     absurd   : Void -> a (+2 metadata)
```

(pr.create took several minutes...)

This PR is probably too small to be worth the overhead, for which apologies.

**Comment by runarorama** [comment]
It's a little weird that this definition can't be parsed, but... `absurd` is a perfectly cromulent function, so I'm inclined to say that's just a limitation of the current implementation of the parser.

**Comment by runarorama** [comment]
Thanks, @atacratic! Merged in base hash #dua5il47ai.
🦄 🌈 ⭐

**Comment by runarorama** [comment]
Idea for a follow-up to this: implement `'{e} Void -> {e} a`. Would that even work?
