### ISSUE TITLE
Add .ascii namespace with various predicates and utilities.

### ISSUE THREAD

**Issue by zenhack** [unisonweb/base_v1#46]
This adds an `ascii` namespace with your usual `isUpper`, `isDigit`, `toLower` etc. stuff that every language has.

Due to performance issues, I had to use git directly to actually push this to my fork, so *hopefully* it still came out ok. Let me know if I've missed anything.

## Code review

```
  The changes summarized below are available for you to review, using the following command:
  
    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/zenhack/base-1:.prs.base._ascii
  
  Added definitions:
  
     ascii._priv.inRange            : Char -> Char -> Char -> Boolean (+1 metadata)
     ascii._priv.inRange.doc        : Doc
     ascii._priv.lowerUpperDiff     : Int (+1 metadata)
     ascii._priv.lowerUpperDiff.doc : Doc
     ascii.doc                      : Doc
     ascii.isAlphaNum               : Char -> Boolean (+1 metadata)
     ascii.isAlphaNum.doc           : Doc
     ascii.isAscii                  : Char -> Boolean (+1 metadata)
     ascii.isAscii.doc              : Doc
     ascii.isBlank                  : Char -> Boolean (+1 metadata)
     ascii.isBlank.doc              : Doc
     ascii.isControl                : Char -> Boolean (+1 metadata)
     ascii.isControl.doc            : Doc
     ascii.isDigit                  : Char -> Boolean (+1 metadata)
     ascii.isDigit.doc              : Doc
     ascii.isGraph                  : Char -> Boolean (+1 metadata)
     ascii.isGraph.doc              : Doc
     ascii.isHexDigit               : Char -> Boolean (+1 metadata)
     ascii.isHexDigit.doc           : Doc
     ascii.isLetter                 : Char -> Boolean (+1 metadata)
     ascii.isLetter.doc             : Doc
     ascii.isLower                  : Char -> Boolean (+1 metadata)
     ascii.isLower.doc              : Doc
     ascii.isPrint                  : Char -> Boolean (+1 metadata)
     ascii.isPrint.doc              : Doc
     ascii.isPunct                  : Char -> Boolean (+1 metadata)
     ascii.isPunct.doc              : Doc
     ascii.isSpace                  : Char -> Boolean (+1 metadata)
     ascii.isSpace.doc              : Doc
     ascii.isUpper                  : Char -> Boolean (+1 metadata)
     ascii.isUpper.doc              : Doc
     ascii.tests.propUpperLower     : [Result] (+2 metadata)
     ascii.tests.propUpperLower.doc : Doc
     ascii.tests.toLower            : [Result] (+1 metadata)
     ascii.tests.toUpper            : [Result] (+1 metadata)
     ascii.toLower                  : Char -> Char (+1 metadata)
     ascii.toLower.doc              : Doc
     ascii.toUpper                  : Char -> Char (+1 metadata)
     ascii.toUpper.doc              : Doc
  
     patch ascii._priv.patch (added 1 updates)
     patch ascii.patch (added 2 updates)
```

**Comment by runarorama** [comment]
Hey Ian! Thanks for this. Can you just verify that you are releasing this code under the MIT license?

**Comment by zenhack** [comment]
SGTM. Do I need to do anything in particular or is this comment sufficient?

**Comment by runarorama** [comment]
I'll get cracking on merging this. A comment like "I am releasing this code under the MIT license" would be good in the meantime.

**Comment by zenhack** [comment]
I am releasing this code under the MIT license.

**Comment by runarorama** [comment]
Merged in base hash #ipcet5vf5t. Thanks @zenhack! 🌈⭐ 

I made some small changes. Like I just moved things out of the _priv namespace, as these seem useful. I also added an `Author` for you and the MIT `License` object with your name as the copyright holder.

For future PRs, please add these in your default metadata (see https://www.unisonweb.org/docs/configuration/) as it's quite tedious to add manually after the fact.

**Comment by zenhack** [comment]
Quoting Rúnar (2020-05-08 15:13:00)

>    I made some small changes. Like I just moved things out of the _priv
>    namespace, as these seem useful. I also added an Author for you and the
>    MIT License object with your name as the copyright holder.

Sounds reasonable.

>    For future PRs, please add these in your default metadata (see
>    [2]https://www.unisonweb.org/docs/configuration/) as it's quite tedious
>    to add manually after the fact.

Will do. Unfortunately this code has been sitting on my hard drive since
before the metadata feature existed, and I've been waiting for a way to
submit -- so I guess I would have had to do it the tedious way anyway,
though sorry to put that burden on you.

**Comment by runarorama** [comment]
No worries, thanks again!
