### ISSUE TITLE
Add nonempty lists

### ISSUE THREAD

**Issue by runarorama** [unisonweb/base_v1#48]
This adds `List.Nonempty`, the type of nonempty lists, and a number of supporting operations.

## Note

Removed `gen.nats1` in favor of the `atLeastOne` combinator that generates a `Nonempty` of the given type.

## Code review

  The changes summarized below are available for you to review, using the
  following command:

    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/runarorama/mybase:._topic.nel

  Added definitions:

    1.  type List.Nonempty a (+5 metadata)
    2.  List.Nonempty.Nonempty                      : a
                                                    -> [a]
                                                    -> Nonempty a
    3.  ┌ List.Nonempty.++                          : Nonempty a
                                                    -> Nonempty a
                                                    -> Nonempty a (+3 metadata)
    4.  └ List.Nonempty.append                      : Nonempty a
                                                    -> Nonempty a
                                                    -> Nonempty a (+3 metadata)
    5.  List.Nonempty.+|                            : a
                                                    -> [a]
                                                    -> Nonempty a (+4 metadata)
    6.  List.Nonempty.append.doc                    : Doc (+2 metadata)
    7.  List.Nonempty.append.tests.associative      : [Test.Result] (+3 metadata)
    8.  List.Nonempty.append.tests.homomorphism     : [Test.Result] (+3 metadata)
    9.  List.Nonempty.cons                          : a
                                                    -> Nonempty a
                                                    -> Nonempty a (+3 metadata)
    10. List.Nonempty.cons.doc                      : Doc (+2 metadata)
    11. List.Nonempty.doc                           : Doc (+2 metadata)
    12. List.Nonempty.examples.construction.ex1     : Nonempty Nat (+2 metadata)
    13. List.Nonempty.examples.construction.ex2     : Optional
                                                      (Nonempty Nat) (+2 metadata)
    14. List.Nonempty.flatMap                       : (a ->{e} Nonempty b)
                                                    -> Nonempty a
                                                    ->{e} Nonempty b (+3 metadata)
    15. List.Nonempty.flatMap.doc                   : Doc (+2 metadata)
    16. List.Nonempty.flatMap.tests.flatMapIdIsjoin : [Test.Result] (+3 metadata)
    17. List.Nonempty.foldMap                       : (b ->{e} b ->{e} b)
                                                    -> (a ->{e} b)
                                                    -> Nonempty a
                                                    ->{e} b (+3 metadata)
    18. List.Nonempty.foldMap.doc                   : Doc (+2 metadata)
    19. List.Nonempty.foldMap.examples.ex1          : Text (+2 metadata)
    20. List.Nonempty.foldMap.test                  : [Test.Result] (+3 metadata)
    21. List.Nonempty.foldl                         : (a ->{e} a ->{e} a)
                                                    -> Nonempty a
                                                    ->{e} a (+3 metadata)
    22. List.Nonempty.foldl.doc                     : Doc (+2 metadata)
    23. List.Nonempty.foldl.test                    : [Test.Result] (+3 metadata)
    24. List.Nonempty.foldr                         : (a ->{e} a ->{e} a)
                                                    -> Nonempty a
                                                    ->{e} a (+3 metadata)
    25. List.Nonempty.foldr.doc                     : Doc (+2 metadata)
    26. List.Nonempty.foldr.test                    : [Test.Result] (+3 metadata)
    27. List.Nonempty.head                          : Nonempty a
                                                    -> a (+3 metadata)
    28. List.Nonempty.head.doc                      : Doc (+2 metadata)
    29. List.Nonempty.head.test                     : [Test.Result] (+3 metadata)
    30. List.Nonempty.init                          : Nonempty a
                                                    -> [a] (+3 metadata)
    31. List.Nonempty.init.doc                      : Doc (+2 metadata)
    32. List.Nonempty.init.test                     : [Test.Result] (+3 metadata)
    33. List.Nonempty.join                          : Nonempty
                                                      (Nonempty a)
                                                    -> Nonempty a (+3 metadata)
    34. List.Nonempty.join.doc                      : Doc (+2 metadata)
    35. List.Nonempty.join.examples.ex1             : Nonempty Nat (+2 metadata)
    36. List.Nonempty.join.tests.associative        : [Test.Result] (+3 metadata)
    37. List.Nonempty.join.tests.unit               : [Test.Result] (+3 metadata)
    38. List.Nonempty.last                          : Nonempty a
                                                    -> a (+3 metadata)
    39. List.Nonempty.last.doc                      : Doc (+2 metadata)
    40. List.Nonempty.last.test                     : [Test.Result] (+3 metadata)
    41. List.Nonempty.map                           : (a ->{e} b)
                                                    -> Nonempty a
                                                    ->{e} Nonempty b (+3 metadata)
    42. List.Nonempty.map.doc                       : Doc (+2 metadata)
    43. List.Nonempty.map.tests.functor             : [Test.Result] (+3 metadata)
    44. List.Nonempty.singleton                     : a
                                                    -> Nonempty a (+3 metadata)
    45. List.Nonempty.singleton.doc                 : Doc (+2 metadata)
    46. List.Nonempty.singleton.test                : [Test.Result] (+3 metadata)
    47. List.Nonempty.size                          : Nonempty a
                                                    -> Nat (+3 metadata)
    48. List.Nonempty.size.doc                      : Doc (+2 metadata)
    49. List.Nonempty.size.test                     : [Test.Result] (+3 metadata)
    50. List.Nonempty.snoc                          : Nonempty a
                                                    -> a
                                                    -> Nonempty a (+3 metadata)
    51. List.Nonempty.snoc.doc                      : Doc (+2 metadata)
    52. List.Nonempty.tail                          : Nonempty a
                                                    -> [a] (+3 metadata)
    53. List.Nonempty.tail.doc                      : Doc (+2 metadata)
    54. List.Nonempty.tail.test                     : [Test.Result] (+3 metadata)
    55. List.Nonempty.toList                        : Nonempty a
                                                    -> [a] (+3 metadata)
    56. List.Nonempty.toList.doc                    : Doc (+2 metadata)
    57. List.Nonempty.|+                            : [a]
                                                    -> a
                                                    -> Nonempty a (+2 metadata)
    58. List.nonempty                               : [a]
                                                    -> Optional
                                                      (Nonempty a) (+3 metadata)
    59. List.nonempty.doc                           : Doc (+2 metadata)
    60. test.gen.atLeastOne                         : '{Gen} a
                                                    -> '{Gen} Nonempty a (+3 metadata)
    61. test.gen.atLeastOne.doc                     : Doc (+2 metadata)

  Removed definitions:

    62. test.gen.nats1     : '{Gen} [Nat]
    63. test.gen.nats1.doc : Doc

**Comment by pchiusano** [comment]
Looks great! Very comprehensive. Merged in #net9h2qktp
