### ISSUE TITLE
Add `Text.split` utility function to split texts on a single character.

### ISSUE THREAD

**Issue by hojberg** [unisonweb/base_v1#49]
A small function for a common operation on Texts.

Few Notes:
* I've diffed against the latest release to get around the issues on trunk right now. If this function exists on trunk, let me know and I'll close the PR.
* I did the author and license metadata after the fact and I'm not sure how best to verify that things are in order?

## Code review

The changes summarized below are available for you to review, using the following command:

```
pull-request.load https://github.com/unisonweb/base:.release._latest https://github.com/hojberg/unison-base:.prs._textSplit
```

Added definitions:

```
Text.split           : Char -> Text -> [Text] (+1 metadata)
Text.split.doc       : Doc
Text.split.tests.ex1 : [Result] (+1 metadata)
Text.split.tests.ex2 : [Result] (+1 metadata)

patch patch (added 1 updates)
```

**Comment by runarorama** [comment]
Hey @hojberg! Thanks for this.

I've made some changes:

* The implementation of `split` can be greatly simplified by using `take`, `drop`, and `indexOf`.
* A property-based test involving the relationship between `intersperse` and `split` seemed like a good thing to add.
* The documentation needed just a bit more fleshing out.
* The PR should be against `.trunk` rather than `.release._latest`.

I put my changes in a PR below. Let me know what you think.

  The changes summarized below are available for you to review, using the
  following command:

    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/runarorama/mybase:._topic.textsplit

  Updates:

    There were 2 auto-propagated updates.

  Added definitions:

     Text.split                       : Char
                                      -> Text
                                      -> [Text] (+4 metadata)
     Text.split.doc                   : Doc (+2 metadata)
     Text.split.examples.ex1          : [Text] (+2 metadata)
     Text.split.examples.ex2          : [Text] (+2 metadata)
     Text.split.test                  : [Test.Result] (+3 metadata)
     test.gen.Text.ascii              : '{Gen} Text (+3 metadata)
     test.gen.Text.ascii.doc          : Doc (+2 metadata)
     test.gen.Text.asciiPrintable     : '{Gen} Text (+3 metadata)
     test.gen.Text.asciiPrintable.doc : Doc (+2 metadata)
     test.gen.oneOf                   : [a] -> '{Gen} a (+2 metadata)

**Comment by hojberg** [comment]
Nice! This looks good to me. I didn't realize half of these functions where in base yet 🎉 

I noticed there's a left over empty `split.tests` namespace, do empty namespaces get skipped in merging?

**Comment by runarorama** [comment]
Alas, they do not

**Comment by pchiusano** [comment]
I was looking at this but got some weird results @runarorama, am not even seeing those new definitions in the diff, and looks like the old min/max are being resurrected? Can you see if you get the same results when you load the PR?

```
.pr49> pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/runarorama/mybase:._topic.textsplit
Removing .unison/v1/paths/_head/dgfu16m1qvcomgu0n75g0665qks240921da0j65vnu10t66c9u13a1k2080jm24889hfhlc59l5nt4cn8ohoqikbqnjq37rdv5e6580
                                                                  
  I checked out https://github.com/unisonweb/base:.trunk to base.
  I checked out https://github.com/runarorama/mybase:._topic.textsplit to head.
  
  The merged result is in merged.
  Use `diff.namespace base merged` to see what's been updated.
  Use `todo merged.patch merged` to see what work is remaining for the merge.
  Use `push https://github.com/unisonweb/base:.trunk merged` to push the changes.

  Here's what's changed in merged after applying the patch at merged.patch:
  
  Updates:
  
    1.   base.Int.max : Int -> Int -> Int
         ↓
    2.   base.Int.max : a -> a -> a
         + 3.   Int.max.doc        : Doc
         + 4.   atacratic.mit_2020 : License
         + 5.   authors.atacratic  : Author
    
*snip*

**Comment by hojberg** [comment]
Oh strange - Runar's branch was working for me last night.

**Comment by runarorama** [comment]
It's the `Propagated` link on these terms, I think. They're definitely gone from both `base` and `merged`, so I suspect this is just a bug in the merge output.

**Comment by runarorama** [comment]
Attempt 2:

```
pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/runarorama/mybase:._topic.textsplit2
```

**Comment by runarorama** [comment]
Alright, merged in base hash #2i1q6hm7u6. Thanks @hojberg !

🌈⭐

**Comment by runarorama** [comment]
Hey, @hojberg, it would be really cool to also have a function that can split on an arbitrary string rather than just a single character. Maybe a little tricky to make it not super slow?

**Comment by hojberg** [comment]
@runarorama definitely! I can take a stab at that
