### ISSUE TITLE
unable to evaluate a sample expression

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base_v1#51]
NOTE: I'm not really sure whether this is an issue with `ucm` or with corrupt data in the base repo. It may be both.

I'm currently using `stack` to build ucm from commit `9dc6a42619072e68d856c1f2605045a3cc14b890` since I'm not able to pull base with the latest release (M1l). It's possible that there's something wrong with my environment, but I don't think that's the issue since expressions like `> 1 + 2` evaluate fine.

If I put `> 1 + 2` in `scratch.u`, `ucm` does what I would expect:

```
.>                                    
                                                                    
  ✅                                                                                                                                     
     
  scratch.u changed.                                                                                                                    
   
  Now evaluating any watch expressions (lines starting with `>`)... Ctrl+C cancels.
                                                                    
                                                                    
    1 | > 1 + 2
          ⧩
          3
```

When I add `> sample 5 nat`, `ucm` crashes with the following:

```
unison: no type declaration for #bpcuh
CallStack (from HasCallStack):
  error, called at src/Unison/Runtime/Rt1.hs:236:20 in unison-parser-typechecker-0.1-1n4fxMa6V58C0oQoOr6uen:Unison.Runtime.Rt1
```

Strangely, if I add the following:

```
test.gen.optional : '{Gen} a -> '{Gen} (Optional a)
test.gen.optional a = Gen.append ('(Gen.sample (yield None))) '(Some !a)
```

then when I save the file I see a new `.>` line that suggests that `ucm` has detected the change to the file, but it's silent and doesn't say that there's a new term that's okay to add. Similarly if I add an expression evaluation below this, I don't see any output for it.

**Comment by runarorama** [comment]
I'm not able to reproduce this here. The hash #bpcuh is the `Gen` ability. Do you have this in your codebase? Try `view #bpcuh`, `names #bpcuh`, and `names Gen`.

**Comment by aryairani** [comment]
~Next step is: verify whether `base` has `.unison/v1/types/*bpcuh*`~ It does!

**Comment by aryairani** [comment]
@ceedubs Would you try creating and attaching [a transcript](https://github.com/unisonweb/unison/blob/master/unison-src/transcripts/hello.md) that reproduces your issue, or confirms that it doesn't reproduce with a transcript?

(Side note: going forward, even issues of unisonweb/base potentially being busted should go in [unisonweb/unison](https://github.com/unisonweb/unison/issues), since `ucm` will have been the tool that busted it.) ;-)  Issues here are just pull requests or bugs in the unison definitions themselves.

**Comment by ceedubs** [comment]
I got the following:

```
.> view #bpcuh                                                                                                                          
                                                                                                                                        
  -- The name _base.test.Gen is assigned to the reference #bpcuh, which is missing from the codebase.                                   
  Tip: You might need to repair the codebase manually.
```

I deleted my `~/.unison` directory and did a fresh pull of `base` and I'm no longer seeing an issue. Sorry in retrospect I realize that it might have been helpful to keep the old version around to try to figure out what had happened. I'm going to close this out and if I run into this issue again I'll try to create a reproducible example.

Thanks for the fast responses!
