### ISSUE TITLE
add test.gen.optional

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base_v1#53]
I haven't added a test based on [this comment](https://github.com/unisonweb/base/issues/34#issuecomment-624866774) on the `test.gen.either` PR, but here is some example output:

```
> sample 5 (test.gen.optional nat)                                                                                                                                           
  ⧩                                                                                                                                                                          
  [None, Some 0, Some 1, Some 2, Some 3]   
```

## Code review

  The changes summarized below are available for you to review, using the following command:
  
    pull-request.load git@github.com:unisonweb/base:.trunk git@github.com:ceedubs/unison-dev:.prs.base._genOption
  
  Added definitions:
  
     test.gen.optional     : '{Gen} a -> '{Gen} Optional a (+3 metadata)
     test.gen.optional.doc : Doc (+2 metadata)

**Comment by runarorama** [comment]
Thanks, @ceedubs! Merged in base hash #fun4nvgche. Keep 'em coming!

🌈⭐

**Comment by runarorama** [comment]
You know, I thought of a way we could maybe test these.

Generate something finite like `Optional Boolean` and check that you generate all of the elements of that type. What do you think?

**Comment by ceedubs** [comment]
@runarorama seems reasonable to me. I've created #55
