### ISSUE TITLE
Additional list functions

### ISSUE THREAD

**Issue by dariooddenino** [unisonweb/base_v1#54]
Added a bunch of list functions that were missing.
Some docs are heavily inspired by the haskell counterpart, not sure if this could be an issue for the license.

## Code review

 The changes summarized below are available for you to review, using the following command:
  
    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/dariooddenino/unisoncode:.prs.base._listextra
  
  Added definitions:
  
     List.dropWhile                       : (a ->{𝕖} Boolean) ->{𝕖} [a] ->{𝕖} [a] (+3 metadata)
     List.dropWhile.doc                   : Doc (+2 metadata)
     List.dropWhile.tests.all             : [Result] (+3 metadata)
     List.dropWhile.tests.middle          : [Result] (+3 metadata)
     List.dropWhile.tests.none            : [Result] (+3 metadata)
     List.group                           : [a] -> [[a]] (+3 metadata)
     List.group.doc                       : Doc (+2 metadata)
     List.group.tests.base                : [Result] (+3 metadata)
     List.groupBy                         : (a ->{𝕖} a ->{𝕖} Boolean)
                                          ->{𝕖} [a]
                                          ->{𝕖} [[a]] (+3 metadata)
     List.groupBy.doc                     : Doc (+2 metadata)
     List.intercalate                     : [a] -> [[a]] -> [a] (+3 metadata)
     List.intercalate.doc                 : Doc (+2 metadata)
     List.intercalate.tests.empty         : [Result] (+3 metadata)
     List.intercalate.tests.empty1        : [Result] (+3 metadata)
     List.intercalate.tests.empty2        : [Result] (+3 metadata)
     List.intercalate.tests.simple        : [Result] (+3 metadata)
     List.intercalate.tests.size          : [Result] (+3 metadata)
     List.intercalateMap                  : (a ->{𝕖} [b]) -> [b] -> [a] ->{𝕖} [b] (+3 metadata)
     List.intercalateMap.doc              : Doc (+2 metadata)
     List.intercalateMap.tests.simple     : [Result] (+3 metadata)
     List.maximum                         : [a] -> Optional a (+3 metadata)
     List.maximum.doc                     : Doc (+2 metadata)
     List.maximum.tests.base              : [Result] (+3 metadata)
     List.maximum.tests.empty             : [Result] (+3 metadata)
     List.minimum                         : [a] -> Optional a (+3 metadata)
     List.minimum.doc                     : Doc (+2 metadata)
     List.minimum.tests.base              : [Result] (+3 metadata)
     List.nonEmptySubsequences            : [a] -> [[a]] (+3 metadata)
     List.nonEmptySubsequences.doc        : Doc (+2 metadata)
     List.nonEmptySubsequences.tests.base : [Result] (+3 metadata)
     List.span                            : (a ->{𝕖} Boolean)
                                          ->{𝕖} [a]
                                          ->{𝕖} ([a], [a]) (+3 metadata)
     List.span.doc                        : Doc (+2 metadata)
     List.span.tests.alle                 : [Result] (+3 metadata)
     List.span.tests.allf                 : [Result] (+3 metadata)
     List.span.tests.middle               : [Result] (+3 metadata)
     List.split                           : (a ->{𝕖} Boolean) ->{𝕖} [a] ->{𝕖} [[a]] (+3 metadata)
     List.split.doc                       : Doc (+2 metadata)
     List.split.tests.base                : [Result] (+3 metadata)
     List.split.tests.double              : [Result] (+3 metadata)
     List.split.tests.empty               : [Result] (+3 metadata)
     List.splitAt                         : Nat -> [a] -> ([a], [a]) (+3 metadata)
     List.splitAt.doc                     : Doc (+2 metadata)
     List.splitAt.tests.base              : [Result] (+3 metadata)
     List.splitAt.tests.ob                : [Result] (+3 metadata)
     List.splitAt.tests.zero              : [Result] (+3 metadata)
     List.stripPrefix                     : [a] ->{𝕖} [a] ->{𝕖} Optional [a] (+3 metadata)
     List.stripPrefix.all                 : [Result] (+3 metadata)
     List.stripPrefix.base                : [Result] (+3 metadata)
     List.stripPrefix.doc                 : Doc (+2 metadata)
     List.stripPrefix.none                : [Result] (+3 metadata)
     List.subsequences                    : [a] -> [[a]] (+3 metadata)
     List.subsequences.doc                : Doc (+2 metadata)
     List.subsequences.tests.base         : [Result] (+3 metadata)
     List.takeWhile                       : (a ->{𝕖} Boolean) ->{𝕖} [a] ->{𝕖} [a] (+3 metadata)
     List.takeWhile.doc                   : Doc (+2 metadata)
     List.takeWhile.tests.all             : [Result] (+3 metadata)
     List.takeWhile.tests.middle          : [Result] (+3 metadata)
     List.takeWhile.tests.none            : [Result] (+3 metadata)

**Comment by runarorama** [comment]
Merged in base hash #dbtnei5vv4. Thanks @dariooddenino! 🌈⭐ 

I made some changes before merging. Please have a look at the differences. Some examples of things I changed:

* I added explicit ability annotations to higher-order functions. Instead of the inferred `𝕖`, these now use explicit effect list `e`. This is generally preferable since effect inference isn't 100% accurate, and I just don't think those `{𝕖}`s look very nice.
* Moved some tests under a `test` namespace.
* Made some documentation more informative and added some examples.
* Changed some definitions so they're tail-recursive.
* Changed some definitions so they don't traverse lists multiple times.

**Comment by dariooddenino** [comment]
Thanks for the fixes, @runarorama ! It seems like I wasn't careful enough :)

What's the easiest way to check the diffs, since they don't show up here?
