### ISSUE TITLE
add gen.optional and gen.either tests

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base_v1#55]
Based on the approach suggested by @runarorama [here](https://github.com/unisonweb/base/issues/53#issuecomment-629573440). The `10` argument being passed to `sample` is arbitrary; I just wanted to make sure that if you sample more items than are in the domain things still work. We could potentially add a version of `sample` that is unbounded, but I wasn't sure if that added much value.

## Code review

  The changes summarized below are available for you to review, using the following command:

    pull-request.load git@github.com:unisonweb/base:.trunk git@github.com:ceedubs/unison-dev:.prs.base._genTests

  Added definitions:

     test.gen.either.test   : [Result] (+3 metadata)
     test.gen.optional.test : [Result] (+3 metadata)

**Comment by runarorama** [comment]
Merged in base hash #h2otv60sgq. Thanks @ceedubs, looks great! 🦄 🌈⭐
