### ISSUE TITLE
use consistent spelling of licenses for ceedubs2020

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base_v1#56]
Since I have lived in the US my whole life, I can't really explain why I spelled it `licences` instead of `licenses` for myself. This changes the name to be consistent with all of the other license metadata.

## Code review

  The changes summarized below are available for you to review, using the following command:

    pull-request.load git@github.com:unisonweb/base:.trunk git@github.com:ceedubs/unison-dev:.prs.base._americanLicense

  Name changes:

    Original                          Changes
     metadata.licences.ceedubs2020     metadata.licenses.ceedubs2020 (added)
                                       metadata.licences.ceedubs2020 (removed)

**Comment by runarorama** [comment]
Merged in base hash #1nu3c1lgqk. That was easy!
