### ISSUE TITLE
Adds List.initialize and List.repeat

### ISSUE THREAD

**Issue by vanev** [unisonweb/base_v1#64]
This pull request introduces two new ways to construct `List`s in unison: **initialize** and **repeat**.

## Code review

The changes summarized below are available for you to review, using the following command:

    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/vanev/unison:.base.prs._listConstructors

  Updates:

     patch patch (added 4 updates)

  Added definitions:

     List.initialize              : Nat ->{𝕖} (Nat ->{𝕖} a) ->{𝕖} [a] (+1 metadata)
     List.initialize.doc          : Doc (+1 metadata)
     List.initialize.examples.ex1 : [Nat]
     List.initialize.tests.ex1    : [Test.Result] (+1 metadata)
     List.repeat                  : Nat -> a -> [a] (+1 metadata)
     List.repeat.doc              : Doc
     List.repeat.examples.ex1     : [Text]
     List.repeat.tests.ex1        : [Test.Result] (+1 metadata)

**Comment by runarorama** [comment]
Hi @vanev! Thanks for this and sorry for the late reply. Could you certify that you are releasing this under the MIT licence and that you have the rights to release this code under that license? Just replying here saying so is fine.

Once I have that I'll get this merged tout-suite.

**Comment by aryairani** [comment]
Wdyt about 
```
Nat ->{𝕖} (Nat ->{𝕖} a) ->{𝕖} [a]
--    ^^^
```
?

I guess parametricity tells us we can't have to worry about it, but would it be better to drop it to either `->` or `->{}` for this sort of thing?  (`->`, I suppose.)

**Comment by runarorama** [comment]
@aryairani I've dropped this type parameter in the version I'm ready to merge.

**Comment by vanev** [comment]
Sorry about the delay here! This code is good to go under MIT. Thanks!

**Comment by runarorama** [comment]
Merged in base hash `#1jef883bie` with some changes:

* Added `metadata.authors.vanev` and linked to these definitions.
* Changed the name of `repeat` to `fill`.
* Cleaned up the patch
* Edited docs for clarity
* Simplified definitions slightly

Thanks! 🌈⭐
