### ISSUE TITLE
Rename Nonempty foldl/r to reduceLeft/Right and add foldLeft/Right

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/base_v1#67]
Resolves #65 (mostly).

## bonus items

I added a generator for nonempty lists to assist in testing the consistency between the `List` and `List.Nonempty` implementations of left/right folds.

## Pending items

- I've added tests but haven't yet added docs. It's currently a bit of a pain to unlink/relink if things change, so I wanted to make sure that things look good before I try to add docs.
- I've named these `List.Nonempty` functions `foldLeft/Right` and `reduceLeft/Right` per the discussion in #65, but I haven't renamed the various `foldl/r` terms that currently exist in base for `List`, `Set`, etc. I don't love the inconsistency, but I wanted to keep the scope of this PR fairly limited. Let me know if you'd rather I make that change in this PR.
- At this point haven't added `reduce` or `fold` aliases for `reduceLeft`/`foldLeft`. If people think that's useful, that's easy to add.

## Random observations

When I renamed `Nonempty.foldl/foldr` I thought that I would have to change their docs to use the new name, and that I would then have to unlink old docs and link the slightly changed docs. But since they were using `@Nonempty.foldl`, the doc was just using a hash and they automagically rendered with the new name with no changes needed 🎉. Very cool.

## Code review

  The changes summarized below are available for you to review, using the following command:

    pull-request.load git@github.com:unisonweb/base:.trunk git@github.com:ceedubs/unison-dev:.prs._base.nelfoldl

  Added definitions:

     List.Nonempty.foldLeft                        : (b ->{e} a ->{e} b)
                                                   -> b
                                                   -> Nonempty a
                                                   ->{e} b (+2 metadata)
     List.Nonempty.foldLeft.tests.listConsistency  : [Result] (+3 metadata)
     List.Nonempty.foldLeft.tests.multiple         : [Result] (+3 metadata)
     List.Nonempty.foldLeft.tests.single           : [Result] (+3 metadata)
     List.Nonempty.foldRight                       : (a ->{e} b ->{e} b)
                                                   -> b
                                                   -> Nonempty a
                                                   ->{e} b (+2 metadata)
     List.Nonempty.foldRight.tests.listConsistency : [Result] (+3 metadata)
     List.Nonempty.foldRight.tests.multiple        : [Result] (+3 metadata)
     List.Nonempty.foldRight.tests.single          : [Result] (+3 metadata)
     test.gen.nonemptyListOf                       : '{Gen} a -> '{Gen} Nonempty a (+2 metadata)

  Name changes:

    Original                     Changes
     List.Nonempty.foldl          List.Nonempty.reduceLeft (added)
                                  List.Nonempty.foldl (removed)

     List.Nonempty.foldl.doc      List.Nonempty.reduceLeft.doc (added)
                                  List.Nonempty.foldl.doc (removed)

     List.Nonempty.foldl.test     List.Nonempty.reduceLeft.test (added)
                                  List.Nonempty.foldl.test (removed)

     List.Nonempty.foldr          List.Nonempty.reduceRight (added)
                                  List.Nonempty.foldr (removed)

     List.Nonempty.foldr.doc      List.Nonempty.reduceRight.doc (added)
                                  List.Nonempty.foldr.doc (removed)

     List.Nonempty.foldr.test     List.Nonempty.reduceRight.test (added)
                                  List.Nonempty.foldr.test (removed)

**Comment by ceedubs** [comment]
Updated to include rename of existing `foldl` and `foldr` terms.

```
The changes summarized below are available for you to review, using the
following command:

  pull-request.load git@github.com:unisonweb/base:.trunk git@github.com:ceedubs/unison-dev:.prs._base.nelfoldl

Added definitions:

   List.Nonempty.foldLeft                        : (b ->{e} a ->{e} b)
                                                 -> b
                                                 -> Nonempty a
                                                 ->{e} b (+3 metadata)
   ┌ List.Nonempty.foldLeft.doc                  : Doc (+2 metadata)
   └ List.foldLeft.doc                           : Doc (+2 metadata)
   List.Nonempty.foldLeft.tests.listConsistency  : [Result] (+3 metadata)
   List.Nonempty.foldLeft.tests.multiple         : [Result] (+3 metadata)
   List.Nonempty.foldLeft.tests.single           : [Result] (+3 metadata)
   List.Nonempty.foldRight                       : (a ->{e} b ->{e} b)
                                                 -> b
                                                 -> Nonempty a
                                                 ->{e} b (+2 metadata)
   List.Nonempty.foldRight.tests.listConsistency : [Result] (+3 metadata)
   List.Nonempty.foldRight.tests.multiple        : [Result] (+3 metadata)
   List.Nonempty.foldRight.tests.single          : [Result] (+3 metadata)
   test.gen.nonemptyListOf                       : '{Gen} a
                                                 -> '{Gen} Nonempty a (+2 metadata)

Name changes:

  Original                          Changes
   List.Nonempty.foldl               List.Nonempty.reduceLeft (added)
                                     List.Nonempty.foldl (removed)
  
   List.Nonempty.foldl.doc           List.Nonempty.reduceLeft.doc (added)
                                     List.Nonempty.foldl.doc (removed)
  
   List.Nonempty.foldl.test          List.Nonempty.reduceLeft.test (added)
                                     List.Nonempty.foldl.test (removed)
  
   List.Nonempty.foldr               List.Nonempty.reduceRight (added)
                                     List.Nonempty.foldr (removed)
  
   List.Nonempty.foldr.doc           List.Nonempty.reduceRight.doc (added)
                                     List.Nonempty.foldr.doc (removed)
  
   List.Nonempty.foldr.test          List.Nonempty.reduceRight.test (added)
                                     List.Nonempty.foldr.test (removed)
  
   List.foldl                        List.foldLeft (added)
                                     List.foldl (removed)
  
   List.foldr                        List.foldRight (added)
                                     List.foldr (removed)
  
   List.foldr.doc                    List.foldRight.doc (added)
                                     List.foldr.doc (removed)
  
   List.foldr.tests.homomorphism     List.foldRight.tests.homomorphism (added)
                                     List.foldr.tests.homomorphism (removed)
  
   Set.foldl                         Set.foldLeft (added)
                                     Set.foldl (removed)
  
   Set.foldl.doc                     Set.foldLeft.doc (added)
                                     Set.foldl.doc (removed)
  
   Set.foldl.tests.homomorphism      Set.foldLeft.tests.homomorphism (added)
                                     Set.foldl.tests.homomorphism (removed)
  
   Set.foldr                         Set.foldRight (added)
                                     Set.foldr (removed)
  
   Set.foldr.doc                     Set.foldRight.doc (added)
                                     Set.foldr.doc (removed)
  
   Set.foldr.tests.homomorphism      Set.foldRight.tests.homomorphism (added)
                                     Set.foldr.tests.homomorphism (removed)

```
```

**Comment by runarorama** [comment]
Merged in base hash #pg2dnkvhju. Thanks @ceedubs !!

🌈🦄
