### ISSUE TITLE
Documentation for .base.io.delay

### ISSUE THREAD

**Issue by fboeller** [unisonweb/base_v1#69]
Added documentation for `delay` to make it clear that it expects microseconds.

```
.prs.base._delaydoc.io> docs delay

  `delay n` delays the next IO operation by `n` microseconds.
  
  *Examples*
  
  ---
  
  Delay by one second:
  
  delay.examples.ex1 =
    'let
      printLine "Before delay"
      delay 1000000
      printLine "After delay"
```

## Code review
                                                               
  The changes summarized below are available for you to review, using the following command:
  
    pull-request.load https://github.com/unisonweb/base:.trunk https://github.com/fboeller/unisoncode:.prs.base._delaydoc
  
  Updates:
  
     io.delay : Nat ->{IO} ()
     +  delay.doc : Doc
  
  Added definitions:
  
     io.delay.doc          : Doc (+2 metadata)
     io.delay.examples.ex1 : ∀ (). () ->{IO} ()
  
     patch io.patch (added 3 updates)

**Comment by runarorama** [comment]
merged in base hash `#oq5fsk4164`. Thanks! 🌈⭐
